/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentation;

import static Data.CUD_SQL.Insert_User;
import Data.User_Creator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.SQLException;

/**
 *
 * @author Admin
 */
public class Admin_Panel extends javax.swing.JPanel {

    /**
     * Creates new form Admin_Panel
     */
    public Admin_Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Pnl_Principal = new javax.swing.JPanel();
        lblIniciarSesion = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        Txt_Usuario = new javax.swing.JTextField();
        Btn_Registrar = new javax.swing.JButton();
        Txt_Contrasena = new javax.swing.JPasswordField();
        lblContrasena2 = new javax.swing.JLabel();
        lblContrasena1 = new javax.swing.JLabel();
        Jcb_Rol = new javax.swing.JComboBox<>();
        lblUsuario2 = new javax.swing.JLabel();
        Txt_Nombre = new javax.swing.JTextField();
        Btn_Inactivo = new javax.swing.JButton();
        Btn_Actualizar = new javax.swing.JButton();
        lblImagen = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Pnl_Principal1 = new javax.swing.JPanel();
        lblIniciarSesion1 = new javax.swing.JLabel();
        lblUsuario1 = new javax.swing.JLabel();
        Txt_Usuario1 = new javax.swing.JTextField();
        Btn_Registrar1 = new javax.swing.JButton();
        lblUsuario3 = new javax.swing.JLabel();
        Txt_Nombre1 = new javax.swing.JTextField();
        Btn_Inactivo1 = new javax.swing.JButton();
        Btn_Actualizar1 = new javax.swing.JButton();
        Txt_Nombre2 = new javax.swing.JTextField();
        Txt_Nombre3 = new javax.swing.JTextField();
        lblUsuario4 = new javax.swing.JLabel();
        lblUsuario5 = new javax.swing.JLabel();
        lblUsuario6 = new javax.swing.JLabel();
        Txt_Nombre5 = new javax.swing.JTextField();
        Txt_Nombre6 = new javax.swing.JTextField();
        lblUsuario7 = new javax.swing.JLabel();
        lblUsuario8 = new javax.swing.JLabel();
        Txt_Nombre7 = new javax.swing.JTextField();
        Txt_Nombre8 = new javax.swing.JTextField();
        lblUsuario9 = new javax.swing.JLabel();
        lblImagen1 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pnl_Principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIniciarSesion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblIniciarSesion.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion.setText("Registro de Usuario");
        Pnl_Principal.add(lblIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 180, 40));

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario.setText("USUARIO(Cédula)");
        Pnl_Principal.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        Txt_Usuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Usuario.setForeground(new java.awt.Color(153, 153, 153));
        Txt_Usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Txt_UsuarioMousePressed(evt);
            }
        });
        Txt_Usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_UsuarioKeyPressed(evt);
            }
        });
        Pnl_Principal.add(Txt_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 350, 40));

        Btn_Registrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_Registrar.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Registrar.setText("Registrar");
        Btn_Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_RegistrarActionPerformed(evt);
            }
        });
        Pnl_Principal.add(Btn_Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, -1, -1));

        Txt_Contrasena.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Contrasena.setForeground(new java.awt.Color(153, 153, 153));
        Txt_Contrasena.setText("********");
        Txt_Contrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Txt_ContrasenaMousePressed(evt);
            }
        });
        Txt_Contrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_ContrasenaKeyPressed(evt);
            }
        });
        Pnl_Principal.add(Txt_Contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 350, 40));

        lblContrasena2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblContrasena2.setForeground(new java.awt.Color(0, 0, 0));
        lblContrasena2.setText("Rol");
        Pnl_Principal.add(lblContrasena2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 40, -1));

        lblContrasena1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblContrasena1.setForeground(new java.awt.Color(0, 0, 0));
        lblContrasena1.setText("CONTRASEÑA");
        Pnl_Principal.add(lblContrasena1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, -1, -1));

        Jcb_Rol.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Jcb_Rol.setForeground(new java.awt.Color(153, 153, 153));
        Jcb_Rol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un rol", "Admin", "Quiropractico", "Entrenador" }));
        Pnl_Principal.add(Jcb_Rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 350, 40));

        lblUsuario2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsuario2.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario2.setText("Nombre");
        Pnl_Principal.add(lblUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

        Txt_Nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Nombre.setForeground(new java.awt.Color(153, 153, 153));
        Txt_Nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Txt_NombreMousePressed(evt);
            }
        });
        Txt_Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_NombreKeyPressed(evt);
            }
        });
        Pnl_Principal.add(Txt_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 350, 40));

        Btn_Inactivo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_Inactivo.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Inactivo.setText("Inactivo");
        Btn_Inactivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_InactivoActionPerformed(evt);
            }
        });
        Pnl_Principal.add(Btn_Inactivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 510, 100, -1));

        Btn_Actualizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_Actualizar.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Actualizar.setText("Actualizar");
        Btn_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ActualizarActionPerformed(evt);
            }
        });
        Pnl_Principal.add(Btn_Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 510, 120, -1));

        lblImagen.setBackground(new java.awt.Color(242, 242, 242));
        lblImagen.setForeground(new java.awt.Color(204, 204, 204));
        Pnl_Principal.add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -2, 820, 760));

        jPanel3.add(Pnl_Principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, -1, 760));

        jTabbedPane1.addTab("Creación de Usuario", jPanel1);

        Pnl_Principal1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIniciarSesion1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblIniciarSesion1.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion1.setText("Registro de Vehiculo");
        Pnl_Principal1.add(lblIniciarSesion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 190, 30));

        lblUsuario1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsuario1.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario1.setText("Número de placa");
        Pnl_Principal1.add(lblUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        Txt_Usuario1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Usuario1.setForeground(new java.awt.Color(153, 153, 153));
        Txt_Usuario1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Txt_Usuario1MousePressed(evt);
            }
        });
        Txt_Usuario1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_Usuario1KeyPressed(evt);
            }
        });
        Pnl_Principal1.add(Txt_Usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 350, 40));

        Btn_Registrar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_Registrar1.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Registrar1.setText("Registrar");
        Btn_Registrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Registrar1ActionPerformed(evt);
            }
        });
        Pnl_Principal1.add(Btn_Registrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 550, 100, -1));

        lblUsuario3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsuario3.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario3.setText("Marca");
        Pnl_Principal1.add(lblUsuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));

        Txt_Nombre1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Nombre1.setForeground(new java.awt.Color(153, 153, 153));
        Txt_Nombre1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Txt_Nombre1MousePressed(evt);
            }
        });
        Txt_Nombre1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_Nombre1KeyPressed(evt);
            }
        });
        Pnl_Principal1.add(Txt_Nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 350, 40));

        Btn_Inactivo1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_Inactivo1.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Inactivo1.setText("Inactivo");
        Btn_Inactivo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Inactivo1ActionPerformed(evt);
            }
        });
        Pnl_Principal1.add(Btn_Inactivo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 550, 110, -1));

        Btn_Actualizar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_Actualizar1.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Actualizar1.setText("Actualizar");
        Btn_Actualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Actualizar1ActionPerformed(evt);
            }
        });
        Pnl_Principal1.add(Btn_Actualizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 550, 120, -1));

        Txt_Nombre2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Nombre2.setForeground(new java.awt.Color(153, 153, 153));
        Txt_Nombre2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Txt_Nombre2MousePressed(evt);
            }
        });
        Txt_Nombre2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_Nombre2KeyPressed(evt);
            }
        });
        Pnl_Principal1.add(Txt_Nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 350, 40));

        Txt_Nombre3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Nombre3.setForeground(new java.awt.Color(153, 153, 153));
        Txt_Nombre3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Txt_Nombre3MousePressed(evt);
            }
        });
        Txt_Nombre3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_Nombre3KeyPressed(evt);
            }
        });
        Pnl_Principal1.add(Txt_Nombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 350, 40));

        lblUsuario4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsuario4.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario4.setText("Año");
        Pnl_Principal1.add(lblUsuario4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));

        lblUsuario5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsuario5.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario5.setText("Modelo");
        Pnl_Principal1.add(lblUsuario5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        lblUsuario6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsuario6.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario6.setText("Color");
        Pnl_Principal1.add(lblUsuario6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, -1, -1));

        Txt_Nombre5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Nombre5.setForeground(new java.awt.Color(153, 153, 153));
        Txt_Nombre5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Txt_Nombre5MousePressed(evt);
            }
        });
        Txt_Nombre5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_Nombre5KeyPressed(evt);
            }
        });
        Pnl_Principal1.add(Txt_Nombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 350, 40));

        Txt_Nombre6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Nombre6.setForeground(new java.awt.Color(153, 153, 153));
        Txt_Nombre6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Txt_Nombre6MousePressed(evt);
            }
        });
        Txt_Nombre6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_Nombre6KeyPressed(evt);
            }
        });
        Pnl_Principal1.add(Txt_Nombre6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 350, 40));

        lblUsuario7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsuario7.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario7.setText("Tipo");
        Pnl_Principal1.add(lblUsuario7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, -1, -1));

        lblUsuario8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsuario8.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario8.setText("Cantidad de Asientos");
        Pnl_Principal1.add(lblUsuario8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, -1, -1));

        Txt_Nombre7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Nombre7.setForeground(new java.awt.Color(153, 153, 153));
        Txt_Nombre7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Txt_Nombre7MousePressed(evt);
            }
        });
        Txt_Nombre7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_Nombre7KeyPressed(evt);
            }
        });
        Pnl_Principal1.add(Txt_Nombre7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 350, 40));

        Txt_Nombre8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Nombre8.setForeground(new java.awt.Color(153, 153, 153));
        Txt_Nombre8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Txt_Nombre8MousePressed(evt);
            }
        });
        Txt_Nombre8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_Nombre8KeyPressed(evt);
            }
        });
        Pnl_Principal1.add(Txt_Nombre8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, 350, 40));

        lblUsuario9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsuario9.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario9.setText("Capacidad de carga");
        Pnl_Principal1.add(lblUsuario9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, -1, -1));

        lblImagen1.setBackground(new java.awt.Color(242, 242, 242));
        lblImagen1.setForeground(new java.awt.Color(204, 204, 204));
        Pnl_Principal1.add(lblImagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -2, 820, 760));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Pnl_Principal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 766, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Pnl_Principal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Creación de Vehículo", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_UsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Txt_UsuarioMousePressed

    }//GEN-LAST:event_Txt_UsuarioMousePressed

    private void Txt_UsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_UsuarioKeyPressed

    }//GEN-LAST:event_Txt_UsuarioKeyPressed

    private void Btn_RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_RegistrarActionPerformed
        int User_Id = Integer.parseInt(Txt_Usuario.getText());
        String Name = Txt_Nombre.getText();
        String Role = (String) Jcb_Rol.getSelectedItem();
        String Password = String.valueOf(Txt_Contrasena.getText());

        User_Creator User = new User_Creator(User_Id, Name, Password, Role);
        int Rows_Affected;
        try {
            Rows_Affected = Insert_User(User);
            if (Rows_Affected != 0) {
                JOptionPane.showMessageDialog(null, "Datos guardados satisfactoriamente", "Aviso importante", JOptionPane.INFORMATION_MESSAGE);
                Txt_Usuario.setText("");
                Txt_Nombre.setText("");
                Jcb_Rol.setSelectedItem("Seleccione un rol");
                Txt_Contrasena.setText("");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Admin_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Btn_RegistrarActionPerformed

    private void Txt_ContrasenaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Txt_ContrasenaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_ContrasenaMousePressed

    private void Txt_ContrasenaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_ContrasenaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_ContrasenaKeyPressed

    private void Txt_NombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Txt_NombreMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_NombreMousePressed

    private void Txt_NombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_NombreKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_NombreKeyPressed

    private void Btn_InactivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_InactivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_InactivoActionPerformed

    private void Btn_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ActualizarActionPerformed
       //gfdgdfgfdgdfgdfgfdgfdgdfgfdgfdgfdgfdgdfgdfgdfgdfgfdgfdgd
       
       
       
       
       
    }//GEN-LAST:event_Btn_ActualizarActionPerformed

    private void Txt_Usuario1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Txt_Usuario1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_Usuario1MousePressed

    private void Txt_Usuario1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_Usuario1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_Usuario1KeyPressed

    private void Btn_Registrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Registrar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Registrar1ActionPerformed

    private void Txt_Nombre1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Txt_Nombre1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_Nombre1MousePressed

    private void Txt_Nombre1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_Nombre1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_Nombre1KeyPressed

    private void Btn_Inactivo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Inactivo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Inactivo1ActionPerformed

    private void Btn_Actualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Actualizar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Actualizar1ActionPerformed

    private void Txt_Nombre2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Txt_Nombre2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_Nombre2MousePressed

    private void Txt_Nombre2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_Nombre2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_Nombre2KeyPressed

    private void Txt_Nombre3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Txt_Nombre3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_Nombre3MousePressed

    private void Txt_Nombre3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_Nombre3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_Nombre3KeyPressed

    private void Txt_Nombre5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Txt_Nombre5MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_Nombre5MousePressed

    private void Txt_Nombre5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_Nombre5KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_Nombre5KeyPressed

    private void Txt_Nombre6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Txt_Nombre6MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_Nombre6MousePressed

    private void Txt_Nombre6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_Nombre6KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_Nombre6KeyPressed

    private void Txt_Nombre7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Txt_Nombre7MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_Nombre7MousePressed

    private void Txt_Nombre7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_Nombre7KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_Nombre7KeyPressed

    private void Txt_Nombre8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Txt_Nombre8MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_Nombre8MousePressed

    private void Txt_Nombre8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_Nombre8KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_Nombre8KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Actualizar;
    private javax.swing.JButton Btn_Actualizar1;
    private javax.swing.JButton Btn_Inactivo;
    private javax.swing.JButton Btn_Inactivo1;
    private javax.swing.JButton Btn_Registrar;
    private javax.swing.JButton Btn_Registrar1;
    private javax.swing.JComboBox<String> Jcb_Rol;
    private javax.swing.JPanel Pnl_Principal;
    private javax.swing.JPanel Pnl_Principal1;
    private javax.swing.JPasswordField Txt_Contrasena;
    private javax.swing.JTextField Txt_Nombre;
    private javax.swing.JTextField Txt_Nombre1;
    private javax.swing.JTextField Txt_Nombre2;
    private javax.swing.JTextField Txt_Nombre3;
    private javax.swing.JTextField Txt_Nombre5;
    private javax.swing.JTextField Txt_Nombre6;
    private javax.swing.JTextField Txt_Nombre7;
    private javax.swing.JTextField Txt_Nombre8;
    private javax.swing.JTextField Txt_Usuario;
    private javax.swing.JTextField Txt_Usuario1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblContrasena1;
    private javax.swing.JLabel lblContrasena2;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblImagen1;
    private javax.swing.JLabel lblIniciarSesion;
    private javax.swing.JLabel lblIniciarSesion1;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuario1;
    private javax.swing.JLabel lblUsuario2;
    private javax.swing.JLabel lblUsuario3;
    private javax.swing.JLabel lblUsuario4;
    private javax.swing.JLabel lblUsuario5;
    private javax.swing.JLabel lblUsuario6;
    private javax.swing.JLabel lblUsuario7;
    private javax.swing.JLabel lblUsuario8;
    private javax.swing.JLabel lblUsuario9;
    // End of variables declaration//GEN-END:variables
}
