/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentation;

import Data.Vehicle_Obj;

/**
 *
 * @author Admin
 */
public class Dispenser_Section extends javax.swing.JPanel {

    /**
     * Creates new form Dispenser_Section
     */
    public Dispenser_Section() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Pnl_Principal = new javax.swing.JPanel();
        lblIniciarSesion = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        Txt_Id_Combustible = new javax.swing.JTextField();
        Btn_Registro_Combustible = new javax.swing.JButton();
        lblContrasena2 = new javax.swing.JLabel();
        lblContrasena1 = new javax.swing.JLabel();
        lblUsuario2 = new javax.swing.JLabel();
        Txt_Precio_Litro = new javax.swing.JTextField();
        Btn_Inactivo_Combustible = new javax.swing.JButton();
        Btn_Actualizar_Combustible = new javax.swing.JButton();
        Txt_Nombre_Combustible = new javax.swing.JTextField();
        Txt_Tipo_Combustible = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        Pnl_Principal1 = new javax.swing.JPanel();
        lblIniciarSesion1 = new javax.swing.JLabel();
        lblUsuario1 = new javax.swing.JLabel();
        Txt_Placa = new javax.swing.JTextField();
        Btn_Registrar_Vehiculo = new javax.swing.JButton();
        lblUsuario3 = new javax.swing.JLabel();
        Txt_Marca = new javax.swing.JTextField();
        Btn_Inactivo1 = new javax.swing.JButton();
        Btn_Actualizar_Vehiculo = new javax.swing.JButton();
        Txt_Ano = new javax.swing.JTextField();
        Txt_Modelo = new javax.swing.JTextField();
        lblUsuario4 = new javax.swing.JLabel();
        lblUsuario5 = new javax.swing.JLabel();
        lblUsuario6 = new javax.swing.JLabel();
        Txt_Color = new javax.swing.JTextField();
        lblUsuario7 = new javax.swing.JLabel();
        lblUsuario8 = new javax.swing.JLabel();
        Txt_Asientos = new javax.swing.JTextField();
        Txt_Capacidad = new javax.swing.JTextField();
        lblUsuario9 = new javax.swing.JLabel();
        Jcb_Tipo = new javax.swing.JComboBox<>();
        lblImagen1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lblImagen = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pnl_Principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIniciarSesion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblIniciarSesion.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion.setText("Registro de combustibles");
        Pnl_Principal.add(lblIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 230, 40));

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario.setText("Id de Combustible");
        Pnl_Principal.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        Txt_Id_Combustible.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Id_Combustible.setForeground(new java.awt.Color(153, 153, 153));
        Txt_Id_Combustible.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Txt_Id_CombustibleMousePressed(evt);
            }
        });
        Txt_Id_Combustible.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_Id_CombustibleKeyPressed(evt);
            }
        });
        Pnl_Principal.add(Txt_Id_Combustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 350, 40));

        Btn_Registro_Combustible.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_Registro_Combustible.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Registro_Combustible.setText("Registrar");
        Btn_Registro_Combustible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Registro_CombustibleActionPerformed(evt);
            }
        });
        Pnl_Principal.add(Btn_Registro_Combustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, -1, -1));

        lblContrasena2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblContrasena2.setForeground(new java.awt.Color(0, 0, 0));
        lblContrasena2.setText("Tipo de combustible(Gasolina)");
        Pnl_Principal.add(lblContrasena2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 220, -1));

        lblContrasena1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblContrasena1.setForeground(new java.awt.Color(0, 0, 0));
        lblContrasena1.setText("Precio por LITRO");
        Pnl_Principal.add(lblContrasena1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, -1, -1));

        lblUsuario2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsuario2.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario2.setText("Nombre");
        Pnl_Principal.add(lblUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

        Txt_Precio_Litro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Precio_Litro.setForeground(new java.awt.Color(153, 153, 153));
        Txt_Precio_Litro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Txt_Precio_LitroMousePressed(evt);
            }
        });
        Txt_Precio_Litro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_Precio_LitroKeyPressed(evt);
            }
        });
        Pnl_Principal.add(Txt_Precio_Litro, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 350, 40));

        Btn_Inactivo_Combustible.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_Inactivo_Combustible.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Inactivo_Combustible.setText("Inactivo");
        Btn_Inactivo_Combustible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Inactivo_CombustibleActionPerformed(evt);
            }
        });
        Pnl_Principal.add(Btn_Inactivo_Combustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 510, 100, -1));

        Btn_Actualizar_Combustible.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_Actualizar_Combustible.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Actualizar_Combustible.setText("Actualizar");
        Btn_Actualizar_Combustible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Actualizar_CombustibleActionPerformed(evt);
            }
        });
        Pnl_Principal.add(Btn_Actualizar_Combustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 510, 120, -1));

        Txt_Nombre_Combustible.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Nombre_Combustible.setForeground(new java.awt.Color(153, 153, 153));
        Txt_Nombre_Combustible.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Txt_Nombre_CombustibleMousePressed(evt);
            }
        });
        Txt_Nombre_Combustible.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_Nombre_CombustibleKeyPressed(evt);
            }
        });
        Pnl_Principal.add(Txt_Nombre_Combustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 350, 40));

        Txt_Tipo_Combustible.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Tipo_Combustible.setForeground(new java.awt.Color(153, 153, 153));
        Txt_Tipo_Combustible.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Txt_Tipo_CombustibleMousePressed(evt);
            }
        });
        Txt_Tipo_Combustible.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_Tipo_CombustibleKeyPressed(evt);
            }
        });
        Pnl_Principal.add(Txt_Tipo_Combustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 350, 40));

        jPanel3.add(Pnl_Principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 760));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, -1, 760));

        jTabbedPane1.addTab("Combustibles", jPanel1);

        Pnl_Principal1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIniciarSesion1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblIniciarSesion1.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion1.setText("Registro de Vehiculo");
        Pnl_Principal1.add(lblIniciarSesion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 190, 30));

        lblUsuario1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsuario1.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario1.setText("Número de placa");
        Pnl_Principal1.add(lblUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        Txt_Placa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Placa.setForeground(new java.awt.Color(153, 153, 153));
        Txt_Placa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Txt_PlacaMousePressed(evt);
            }
        });
        Txt_Placa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_PlacaKeyPressed(evt);
            }
        });
        Pnl_Principal1.add(Txt_Placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 350, 40));

        Btn_Registrar_Vehiculo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_Registrar_Vehiculo.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Registrar_Vehiculo.setText("Registrar");
        Btn_Registrar_Vehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Registrar_VehiculoActionPerformed(evt);
            }
        });
        Pnl_Principal1.add(Btn_Registrar_Vehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 550, 100, -1));

        lblUsuario3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsuario3.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario3.setText("Marca");
        Pnl_Principal1.add(lblUsuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));

        Txt_Marca.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Marca.setForeground(new java.awt.Color(153, 153, 153));
        Txt_Marca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Txt_MarcaMousePressed(evt);
            }
        });
        Txt_Marca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_MarcaKeyPressed(evt);
            }
        });
        Pnl_Principal1.add(Txt_Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 350, 40));

        Btn_Inactivo1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_Inactivo1.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Inactivo1.setText("Inactivo");
        Btn_Inactivo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Inactivo1ActionPerformed(evt);
            }
        });
        Pnl_Principal1.add(Btn_Inactivo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 550, 110, -1));

        Btn_Actualizar_Vehiculo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_Actualizar_Vehiculo.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Actualizar_Vehiculo.setText("Actualizar");
        Btn_Actualizar_Vehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Actualizar_VehiculoActionPerformed(evt);
            }
        });
        Pnl_Principal1.add(Btn_Actualizar_Vehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 550, 120, -1));

        Txt_Ano.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Ano.setForeground(new java.awt.Color(153, 153, 153));
        Txt_Ano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Txt_AnoMousePressed(evt);
            }
        });
        Txt_Ano.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_AnoKeyPressed(evt);
            }
        });
        Pnl_Principal1.add(Txt_Ano, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 350, 40));

        Txt_Modelo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Modelo.setForeground(new java.awt.Color(153, 153, 153));
        Txt_Modelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Txt_ModeloMousePressed(evt);
            }
        });
        Txt_Modelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_ModeloKeyPressed(evt);
            }
        });
        Pnl_Principal1.add(Txt_Modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 350, 40));

        lblUsuario4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsuario4.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario4.setText("Año");
        Pnl_Principal1.add(lblUsuario4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));

        lblUsuario5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsuario5.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario5.setText("Modelo");
        Pnl_Principal1.add(lblUsuario5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        lblUsuario6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsuario6.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario6.setText("Color");
        Pnl_Principal1.add(lblUsuario6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, -1, -1));

        Txt_Color.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Color.setForeground(new java.awt.Color(153, 153, 153));
        Txt_Color.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Txt_ColorMousePressed(evt);
            }
        });
        Txt_Color.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_ColorKeyPressed(evt);
            }
        });
        Pnl_Principal1.add(Txt_Color, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 350, 40));

        lblUsuario7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsuario7.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario7.setText("Tipo");
        Pnl_Principal1.add(lblUsuario7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, -1, -1));

        lblUsuario8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsuario8.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario8.setText("Cantidad de Asientos");
        Pnl_Principal1.add(lblUsuario8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, -1, -1));

        Txt_Asientos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Asientos.setForeground(new java.awt.Color(153, 153, 153));
        Txt_Asientos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Txt_AsientosMousePressed(evt);
            }
        });
        Txt_Asientos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_AsientosKeyPressed(evt);
            }
        });
        Pnl_Principal1.add(Txt_Asientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 350, 40));

        Txt_Capacidad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Capacidad.setForeground(new java.awt.Color(153, 153, 153));
        Txt_Capacidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Txt_CapacidadMousePressed(evt);
            }
        });
        Txt_Capacidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_CapacidadKeyPressed(evt);
            }
        });
        Pnl_Principal1.add(Txt_Capacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, 350, 40));

        lblUsuario9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsuario9.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario9.setText("Capacidad de carga");
        Pnl_Principal1.add(lblUsuario9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, -1, -1));

        Jcb_Tipo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Jcb_Tipo.setForeground(new java.awt.Color(153, 153, 153));
        Jcb_Tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un tipo:", "Automóvil", "Camión", "Furgoneta", "Autobús", "Motocicleta", "Bicicleta", "Camioneta", "SUV", "Deportivo", "Minivan", "Tractor", "Coche eléctrico", "Vehículo de carga", "Vehículo todoterreno", "Vehículo de lujo", "Vehículo de trabajo", "Vehículo de emergencias", "Vehículo público", "Vehículo híbrido", "Vehículo comercial" }));
        Pnl_Principal1.add(Jcb_Tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 350, 40));

        lblImagen1.setBackground(new java.awt.Color(242, 242, 242));
        lblImagen1.setForeground(new java.awt.Color(204, 204, 204));
        Pnl_Principal1.add(lblImagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -2, 820, 760));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Pnl_Principal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 766, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Pnl_Principal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Tanques Combustible", jPanel2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 766, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Ingreso de combustible", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 766, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Dispensadores", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 766, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Dispensado de combustible", jPanel6);

        lblImagen.setBackground(new java.awt.Color(242, 242, 242));
        lblImagen.setForeground(new java.awt.Color(204, 204, 204));
        jTabbedPane1.addTab("tab6", lblImagen);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>                        

    private void Txt_Id_CombustibleMousePressed(java.awt.event.MouseEvent evt) {                                                

    }                                               

    private void Txt_Id_CombustibleKeyPressed(java.awt.event.KeyEvent evt) {                                              

    }                                             

    private void Btn_Registro_CombustibleActionPerformed(java.awt.event.ActionEvent evt) {                                                         
        int User_Id = Integer.parseInt(Txt_Id_Combustible.getText());
        String Name = Txt_Precio_Litro.getText();
        String Role = (String) Jcb_Rol.getSelectedItem();
        String Password = String.valueOf(Txt_Contrasena.getText());

        User_Creator User = new User_Creator(User_Id, Name, Password, Role);
        int Rows_Affected;
        try {
            Rows_Affected = Insert_User(User);
            if (Rows_Affected != 0) {
                Txt_Id_Combustible.setText("");
                Txt_Precio_Litro.setText("");
                Jcb_Rol.setSelectedItem("Seleccione un rol");
                Txt_Contrasena.setText("");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Admin_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                                        

    private void Txt_Precio_LitroMousePressed(java.awt.event.MouseEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void Txt_Precio_LitroKeyPressed(java.awt.event.KeyEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void Btn_Inactivo_CombustibleActionPerformed(java.awt.event.ActionEvent evt) {                                                         
        // TODO add your handling code here:
    }                                                        

    private void Btn_Actualizar_CombustibleActionPerformed(java.awt.event.ActionEvent evt) {                                                           
        int User_Id = Integer.parseInt(Txt_Id_Combustible.getText());
        String Name = Txt_Precio_Litro.getText();
        String Role = (String) Jcb_Rol.getSelectedItem();
        String Password = String.valueOf(Txt_Contrasena.getText());

        User_Creator User = new User_Creator(User_Id, Name, Password, Role);
        int Rows_Affected;
        try {
            Rows_Affected = Update_User(User);
            if (Rows_Affected != 0) {
                Txt_Id_Combustible.setText("");
                Txt_Precio_Litro.setText("");
                Jcb_Rol.setSelectedItem("Seleccione un rol");
                Txt_Contrasena.setText("");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Admin_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }                                                          

    private void Txt_PlacaMousePressed(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void Txt_PlacaKeyPressed(java.awt.event.KeyEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void Btn_Registrar_VehiculoActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        int Fuel_Id = Integer.valueOf(Txt_Id_Combustible.getText());

        Fuel_Obj Vehicle = new Fuel_Obj();

        try {
            Insert_Vehicle(Vehicle);
            Txt_Placa.setText("");
            Txt_Marca.setText("");
            Txt_Modelo.setText("");
            Txt_Ano.setText("");
            Txt_Color.setText("");
            Jcb_Tipo.setSelectedItem("Seleccione un tipo:");
            Txt_Asientos.setText("");
            Txt_Capacidad.setText("");

        } catch (SQLException ex) {
            Logger.getLogger(Admin_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                                      

    private void Txt_MarcaMousePressed(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void Txt_MarcaKeyPressed(java.awt.event.KeyEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void Btn_Inactivo1ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void Btn_Actualizar_VehiculoActionPerformed(java.awt.event.ActionEvent evt) {                                                        
        String License_Plate = Txt_Placa.getText();
        String Brand = Txt_Marca.getText();
        String Model = Txt_Modelo.getText();
        int Year = Integer.valueOf(Txt_Ano.getText());
        String Color = Txt_Color.getText();
        String Type = (String) Jcb_Tipo.getSelectedItem();
        int Seating = Integer.valueOf(Txt_Asientos.getText());
        float Capacity = Float.parseFloat(Txt_Capacidad.getText());

        Vehicle_Obj Vehicle = new Vehicle_Obj(License_Plate, Brand, Model, Year, Color, Type, Seating, Capacity);

        try {
            Update_Vehicle(Vehicle);
            Txt_Placa.setText("");
            Txt_Marca.setText("");
            Txt_Modelo.setText("");
            Txt_Ano.setText("");
            Txt_Color.setText("");
            Jcb_Tipo.setSelectedItem("Seleccione un tipo:");
            Txt_Asientos.setText("");
            Txt_Capacidad.setText("");

        } catch (SQLException ex) {
            Logger.getLogger(Admin_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                                       

    private void Txt_AnoMousePressed(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void Txt_AnoKeyPressed(java.awt.event.KeyEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void Txt_ModeloMousePressed(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void Txt_ModeloKeyPressed(java.awt.event.KeyEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void Txt_ColorMousePressed(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void Txt_ColorKeyPressed(java.awt.event.KeyEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void Txt_AsientosMousePressed(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void Txt_AsientosKeyPressed(java.awt.event.KeyEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void Txt_CapacidadMousePressed(java.awt.event.MouseEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void Txt_CapacidadKeyPressed(java.awt.event.KeyEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void Txt_Nombre_CombustibleMousePressed(java.awt.event.MouseEvent evt) {                                                    
        // TODO add your handling code here:
    }                                                   

    private void Txt_Nombre_CombustibleKeyPressed(java.awt.event.KeyEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void Txt_Tipo_CombustibleMousePressed(java.awt.event.MouseEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void Txt_Tipo_CombustibleKeyPressed(java.awt.event.KeyEvent evt) {                                                
        // TODO add your handling code here:
    }                                               


    // Variables declaration - do not modify                     
    private javax.swing.JButton Btn_Actualizar_Combustible;
    private javax.swing.JButton Btn_Actualizar_Vehiculo;
    private javax.swing.JButton Btn_Inactivo1;
    private javax.swing.JButton Btn_Inactivo_Combustible;
    private javax.swing.JButton Btn_Registrar_Vehiculo;
    private javax.swing.JButton Btn_Registro_Combustible;
    private javax.swing.JComboBox<String> Jcb_Tipo;
    private javax.swing.JPanel Pnl_Principal;
    private javax.swing.JPanel Pnl_Principal1;
    private javax.swing.JTextField Txt_Ano;
    private javax.swing.JTextField Txt_Asientos;
    private javax.swing.JTextField Txt_Capacidad;
    private javax.swing.JTextField Txt_Color;
    private javax.swing.JTextField Txt_Id_Combustible;
    private javax.swing.JTextField Txt_Marca;
    private javax.swing.JTextField Txt_Modelo;
    private javax.swing.JTextField Txt_Nombre_Combustible;
    private javax.swing.JTextField Txt_Placa;
    private javax.swing.JTextField Txt_Precio_Litro;
    private javax.swing.JTextField Txt_Tipo_Combustible;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblContrasena1;
    private javax.swing.JLabel lblContrasena2;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblImagen1;
    private javax.swing.JLabel lblIniciarSesion;
    private javax.swing.JLabel lblIniciarSesion1;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuario1;
    private javax.swing.JLabel lblUsuario2;
    private javax.swing.JLabel lblUsuario3;
    private javax.swing.JLabel lblUsuario4;
    private javax.swing.JLabel lblUsuario5;
    private javax.swing.JLabel lblUsuario6;
    private javax.swing.JLabel lblUsuario7;
    private javax.swing.JLabel lblUsuario8;
    private javax.swing.JLabel lblUsuario9;
    // End of variables declaration                   
}
