/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentation;

import Data.CUD_SQL;
import Data.Fuel_Obj;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Admin
 */
public class Dispenser_Section extends javax.swing.JPanel {

    /**
     * Creates new form Dispenserr_Section
     */
    public Dispenser_Section() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Pnl_Principal = new javax.swing.JPanel();
        lblIniciarSesion = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        Txt_Id_Combustible = new javax.swing.JTextField();
        Btn_Registro_Combustible = new javax.swing.JButton();
        lblContrasena2 = new javax.swing.JLabel();
        lblContrasena1 = new javax.swing.JLabel();
        lblUsuario2 = new javax.swing.JLabel();
        Txt_Precio_Litro = new javax.swing.JTextField();
        Btn_Inactivo_Combustible = new javax.swing.JButton();
        Btn_Actualizar_Combustible = new javax.swing.JButton();
        Txt_Nombre_Combustible = new javax.swing.JTextField();
        Txt_Tipo_Combustible = new javax.swing.JTextField();
        lblImagen = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Pnl_Principal1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pnl_Principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIniciarSesion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblIniciarSesion.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion.setText("Registro de combustibles");
        Pnl_Principal.add(lblIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 230, 40));

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario.setText("Id de Combustible");
        Pnl_Principal.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        Txt_Id_Combustible.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Id_Combustible.setForeground(new java.awt.Color(153, 153, 153));
        Pnl_Principal.add(Txt_Id_Combustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 350, 40));

        Btn_Registro_Combustible.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_Registro_Combustible.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Registro_Combustible.setText("Registrar");
        Btn_Registro_Combustible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Registro_CombustibleActionPerformed(evt);
            }
        });
        Pnl_Principal.add(Btn_Registro_Combustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, -1, -1));

        lblContrasena2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblContrasena2.setForeground(new java.awt.Color(0, 0, 0));
        lblContrasena2.setText("Tipo de combustible(Gasolina)");
        Pnl_Principal.add(lblContrasena2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 220, -1));

        lblContrasena1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblContrasena1.setForeground(new java.awt.Color(0, 0, 0));
        lblContrasena1.setText("Precio por LITRO");
        Pnl_Principal.add(lblContrasena1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, -1, -1));

        lblUsuario2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsuario2.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario2.setText("Nombre");
        Pnl_Principal.add(lblUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

        Txt_Precio_Litro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Precio_Litro.setForeground(new java.awt.Color(153, 153, 153));
        Pnl_Principal.add(Txt_Precio_Litro, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 350, 40));

        Btn_Inactivo_Combustible.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_Inactivo_Combustible.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Inactivo_Combustible.setText("Inactivo");
        Btn_Inactivo_Combustible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Inactivo_CombustibleActionPerformed(evt);
            }
        });
        Pnl_Principal.add(Btn_Inactivo_Combustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 510, 100, -1));

        Btn_Actualizar_Combustible.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_Actualizar_Combustible.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Actualizar_Combustible.setText("Actualizar");
        Btn_Actualizar_Combustible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Actualizar_CombustibleActionPerformed(evt);
            }
        });
        Pnl_Principal.add(Btn_Actualizar_Combustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 510, 120, -1));

        Txt_Nombre_Combustible.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Nombre_Combustible.setForeground(new java.awt.Color(153, 153, 153));
        Pnl_Principal.add(Txt_Nombre_Combustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 350, 40));

        Txt_Tipo_Combustible.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Tipo_Combustible.setForeground(new java.awt.Color(153, 153, 153));
        Pnl_Principal.add(Txt_Tipo_Combustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 350, 40));

        jPanel3.add(Pnl_Principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 760));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, -1, 760));

        lblImagen.setBackground(new java.awt.Color(242, 242, 242));
        lblImagen.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 740));

        jTabbedPane1.addTab("Combustibles", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pnl_Principal1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(Pnl_Principal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 820, 760));

        jTabbedPane1.addTab("Tanques Combustible", jPanel2);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("Ingreso de combustible", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("Dispensadores", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("Dispensado de combustible", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_Actualizar_CombustibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Actualizar_CombustibleActionPerformed
        int Fuel_Id = Integer.parseInt(Txt_Id_Combustible.getText());
        String Fuel_Name = Txt_Nombre_Combustible.getText();
        String Type = Txt_Tipo_Combustible.getText();
        float Price = Float.parseFloat(Txt_Precio_Litro.getText());

        Fuel_Obj Fuel = new Fuel_Obj(Fuel_Id, Fuel_Name, Type, Price, 1);
        try {
            int Affected_Rows = CUD_SQL.Update_Fuel(Fuel);
            if (Affected_Rows != 0) {
                Txt_Id_Combustible.setText("");
                Txt_Nombre_Combustible.setText("");
                Txt_Tipo_Combustible.setText("");
                Txt_Precio_Litro.setText("");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Dispenser_Section.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Btn_Actualizar_CombustibleActionPerformed

    private void Btn_Inactivo_CombustibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Inactivo_CombustibleActionPerformed
        int Fuel_Id = Integer.parseInt(Txt_Id_Combustible.getText());

        int Rows_Affected;

        try {

            Rows_Affected = CUD_SQL.Update_Fuel_Status(Fuel_Id, 0);
            if (Rows_Affected != 0) {
                Txt_Id_Combustible.setText("");
                Txt_Nombre_Combustible.setText("");
                Txt_Tipo_Combustible.setText("");
                Txt_Precio_Litro.setText("");
            }

        } catch (SQLException ex) {
            Logger.getLogger(Admin_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_Btn_Inactivo_CombustibleActionPerformed

    private void Btn_Registro_CombustibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Registro_CombustibleActionPerformed
        int Fuel_Id = Integer.parseInt(Txt_Id_Combustible.getText());
        String Fuel_Name = Txt_Nombre_Combustible.getText();
        String Type = Txt_Tipo_Combustible.getText();
        float Price = Float.parseFloat(Txt_Precio_Litro.getText());

        Fuel_Obj Fuel = new Fuel_Obj(Fuel_Id, Fuel_Name, Type, Price, 1);
        try {
            int Affected_Rows = CUD_SQL.Insert_Fuel(Fuel);
            if (Affected_Rows != 0) {
                Txt_Id_Combustible.setText("");
                Txt_Nombre_Combustible.setText("");
                Txt_Tipo_Combustible.setText("");
                Txt_Precio_Litro.setText("");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Dispenser_Section.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Btn_Registro_CombustibleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Actualizar_Combustible;
    private javax.swing.JButton Btn_Inactivo_Combustible;
    private javax.swing.JButton Btn_Registro_Combustible;
    private javax.swing.JPanel Pnl_Principal;
    private javax.swing.JPanel Pnl_Principal1;
    private javax.swing.JTextField Txt_Id_Combustible;
    private javax.swing.JTextField Txt_Nombre_Combustible;
    private javax.swing.JTextField Txt_Precio_Litro;
    private javax.swing.JTextField Txt_Tipo_Combustible;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblContrasena1;
    private javax.swing.JLabel lblContrasena2;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblIniciarSesion;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuario2;
    // End of variables declaration//GEN-END:variables
}
