/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentation;

import Data.Binnacle_Obj;
import Data.CUD_SQL;
import static Data.CUD_SQL.Insert_Binnacle_Record;
import Data.Connection_SQL;
import Data.Dispenser_Obj;
import Data.Fuel_Entry_Exit_Obj;
import Data.Fuel_Obj;
import Data.Fuel_Tank_Obj;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Dispenser_Section extends javax.swing.JPanel {

    /**
     * Creates new form Dispenser_Section
     */
    int Actual_User = Log_In.User_Id;

    public Dispenser_Section() throws SQLException {
        initComponents();
        Default_JCB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Pnl_Principal = new javax.swing.JPanel();
        lblIniciarSesion = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        Txt_Id_Combustible = new javax.swing.JTextField();
        Btn_Registro_Combustible = new javax.swing.JButton();
        lblContrasena2 = new javax.swing.JLabel();
        lblContrasena1 = new javax.swing.JLabel();
        lblUsuario2 = new javax.swing.JLabel();
        Txt_Precio_Litro = new javax.swing.JTextField();
        Btn_Actualizar_Combustible = new javax.swing.JButton();
        Txt_Nombre_Combustible = new javax.swing.JTextField();
        Txt_Tipo_Combustible = new javax.swing.JTextField();
        lblImagen = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Pnl_Principal1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        lblIniciarSesion4 = new javax.swing.JLabel();
        Txt_Id_Dispensador = new javax.swing.JTextField();
        lblIniciarSesion7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxA_Descripcion_Dispensador = new javax.swing.JTextArea();
        lblIniciarSesion5 = new javax.swing.JLabel();
        Btn_Registrar_Dispensador = new javax.swing.JButton();
        Btn_Actualizar_Dispensador = new javax.swing.JButton();
        Jcb_Id_Tanque = new javax.swing.JComboBox<>();
        lblIniciarSesion8 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        lblIniciarSesion9 = new javax.swing.JLabel();
        Txt_Id_Tanque = new javax.swing.JTextField();
        Txt_Capacidad_Tanque = new javax.swing.JTextField();
        lblIniciarSesion10 = new javax.swing.JLabel();
        lblIniciarSesion11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxA_Descripcion_Tanque = new javax.swing.JTextArea();
        lblIniciarSesion12 = new javax.swing.JLabel();
        Btn_Registrar_Tanque = new javax.swing.JButton();
        Btn_Actualizar_Tanque = new javax.swing.JButton();
        Jcb_Gasolina_Tanque = new javax.swing.JComboBox<>();
        lblIniciarSesion13 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        Pnl_Principal2 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        lblIniciarSesion17 = new javax.swing.JLabel();
        Txt_Id_Ingreso = new javax.swing.JTextField();
        lblIniciarSesion18 = new javax.swing.JLabel();
        Btn_Registrar_Ingreso_Combustible = new javax.swing.JButton();
        Btn_Actualizar_Ingreso_Combustible = new javax.swing.JButton();
        lblIniciarSesion21 = new javax.swing.JLabel();
        lblIniciarSesion22 = new javax.swing.JLabel();
        Txt_Ingreso_Litros = new javax.swing.JTextField();
        lblIniciarSesion31 = new javax.swing.JLabel();
        DCC_Fecha_Ingreso = new datechooser.beans.DateChooserCombo();
        Jcb_Disp = new javax.swing.JComboBox<>();
        jPanel16 = new javax.swing.JPanel();
        lblIniciarSesion24 = new javax.swing.JLabel();
        Txt_Id_Dispensador_Combustible = new javax.swing.JTextField();
        lblIniciarSesion25 = new javax.swing.JLabel();
        lblIniciarSesion26 = new javax.swing.JLabel();
        Btn_Registrar_Dispensado_Combustible = new javax.swing.JButton();
        Btn_Actualizar_Dispensado_Combustible = new javax.swing.JButton();
        Jcb_Matricula = new javax.swing.JComboBox<>();
        lblIniciarSesion28 = new javax.swing.JLabel();
        lblIniciarSesion29 = new javax.swing.JLabel();
        Txt_Kilometraje = new javax.swing.JTextField();
        lblIniciarSesion30 = new javax.swing.JLabel();
        lblIniciarSesion27 = new javax.swing.JLabel();
        Txt_Litros_Retiro = new javax.swing.JTextField();
        DCC_Fecha_Combustible = new datechooser.beans.DateChooserCombo();
        Jcb_Id_Dispensador = new javax.swing.JComboBox<>();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pnl_Principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIniciarSesion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblIniciarSesion.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion.setText("Registro de combustibles");
        Pnl_Principal.add(lblIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 230, 40));

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario.setText("Id de Combustible");
        Pnl_Principal.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        Txt_Id_Combustible.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Id_Combustible.setForeground(new java.awt.Color(153, 153, 153));
        Pnl_Principal.add(Txt_Id_Combustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 350, 40));

        Btn_Registro_Combustible.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_Registro_Combustible.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Registro_Combustible.setText("Registrar");
        Btn_Registro_Combustible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Registro_CombustibleActionPerformed(evt);
            }
        });
        Pnl_Principal.add(Btn_Registro_Combustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 510, -1, -1));

        lblContrasena2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblContrasena2.setForeground(new java.awt.Color(0, 0, 0));
        lblContrasena2.setText("Tipo de combustible(Gasolina)");
        Pnl_Principal.add(lblContrasena2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 220, -1));

        lblContrasena1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblContrasena1.setForeground(new java.awt.Color(0, 0, 0));
        lblContrasena1.setText("Precio por LITRO");
        Pnl_Principal.add(lblContrasena1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, -1, -1));

        lblUsuario2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsuario2.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario2.setText("Nombre");
        Pnl_Principal.add(lblUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

        Txt_Precio_Litro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Precio_Litro.setForeground(new java.awt.Color(153, 153, 153));
        Pnl_Principal.add(Txt_Precio_Litro, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 350, 40));

        Btn_Actualizar_Combustible.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_Actualizar_Combustible.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Actualizar_Combustible.setText("Actualizar");
        Btn_Actualizar_Combustible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Actualizar_CombustibleActionPerformed(evt);
            }
        });
        Pnl_Principal.add(Btn_Actualizar_Combustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 510, 120, -1));

        Txt_Nombre_Combustible.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Nombre_Combustible.setForeground(new java.awt.Color(153, 153, 153));
        Pnl_Principal.add(Txt_Nombre_Combustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 350, 40));

        Txt_Tipo_Combustible.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Tipo_Combustible.setForeground(new java.awt.Color(153, 153, 153));
        Pnl_Principal.add(Txt_Tipo_Combustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 350, 40));

        jPanel3.add(Pnl_Principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 760));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, -1, 760));

        lblImagen.setBackground(new java.awt.Color(242, 242, 242));
        lblImagen.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 740));

        jTabbedPane1.addTab("Combustibles", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pnl_Principal1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIniciarSesion4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIniciarSesion4.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion4.setText("Id del dispensador");
        jPanel12.add(lblIniciarSesion4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 147, -1));

        Txt_Id_Dispensador.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Id_Dispensador.setForeground(new java.awt.Color(153, 153, 153));
        jPanel12.add(Txt_Id_Dispensador, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 170, -1));

        lblIniciarSesion7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIniciarSesion7.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion7.setText("Id del Tanque");
        jPanel12.add(lblIniciarSesion7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 170, -1));

        TxA_Descripcion_Dispensador.setColumns(20);
        TxA_Descripcion_Dispensador.setRows(5);
        jScrollPane1.setViewportView(TxA_Descripcion_Dispensador);

        jPanel12.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 360, 120));

        lblIniciarSesion5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIniciarSesion5.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion5.setText("Descripción");
        jPanel12.add(lblIniciarSesion5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 79, -1));

        Btn_Registrar_Dispensador.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn_Registrar_Dispensador.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Registrar_Dispensador.setText("Registrar");
        Btn_Registrar_Dispensador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Registrar_DispensadorActionPerformed(evt);
            }
        });
        jPanel12.add(Btn_Registrar_Dispensador, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 90, -1));

        Btn_Actualizar_Dispensador.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn_Actualizar_Dispensador.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Actualizar_Dispensador.setText("Actualizar");
        Btn_Actualizar_Dispensador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Actualizar_DispensadorActionPerformed(evt);
            }
        });
        jPanel12.add(Btn_Actualizar_Dispensador, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 100, -1));

        Jcb_Id_Tanque.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Jcb_Id_Tanque.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion" }));
        jPanel12.add(Jcb_Id_Tanque, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 170, -1));

        lblIniciarSesion8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblIniciarSesion8.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion8.setText("Dispensador");
        jPanel12.add(lblIniciarSesion8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        jPanel8.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 810, 290));

        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIniciarSesion9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIniciarSesion9.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion9.setText("Id del tanque");
        jPanel13.add(lblIniciarSesion9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 147, -1));

        Txt_Id_Tanque.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Id_Tanque.setForeground(new java.awt.Color(153, 153, 153));
        jPanel13.add(Txt_Id_Tanque, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 170, -1));

        Txt_Capacidad_Tanque.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Capacidad_Tanque.setForeground(new java.awt.Color(153, 153, 153));
        jPanel13.add(Txt_Capacidad_Tanque, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 170, -1));

        lblIniciarSesion10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIniciarSesion10.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion10.setText("Capacidad");
        jPanel13.add(lblIniciarSesion10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 147, -1));

        lblIniciarSesion11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIniciarSesion11.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion11.setText("Tipo de Gasolina");
        jPanel13.add(lblIniciarSesion11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 147, -1));

        TxA_Descripcion_Tanque.setColumns(20);
        TxA_Descripcion_Tanque.setRows(5);
        jScrollPane2.setViewportView(TxA_Descripcion_Tanque);

        jPanel13.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 360, 120));

        lblIniciarSesion12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIniciarSesion12.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion12.setText("Descripción");
        jPanel13.add(lblIniciarSesion12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 79, -1));

        Btn_Registrar_Tanque.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn_Registrar_Tanque.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Registrar_Tanque.setText("Registrar");
        Btn_Registrar_Tanque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Registrar_TanqueActionPerformed(evt);
            }
        });
        jPanel13.add(Btn_Registrar_Tanque, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 90, -1));

        Btn_Actualizar_Tanque.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn_Actualizar_Tanque.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Actualizar_Tanque.setText("Actualizar");
        Btn_Actualizar_Tanque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Actualizar_TanqueActionPerformed(evt);
            }
        });
        jPanel13.add(Btn_Actualizar_Tanque, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 100, -1));

        Jcb_Gasolina_Tanque.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Jcb_Gasolina_Tanque.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion" }));
        jPanel13.add(Jcb_Gasolina_Tanque, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 170, -1));

        lblIniciarSesion13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblIniciarSesion13.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion13.setText("Tanques de Combustible");
        jPanel13.add(lblIniciarSesion13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        jPanel8.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 810, 350));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 760));

        Pnl_Principal1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.add(Pnl_Principal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 820, 760));

        jTabbedPane1.addTab("Tanque/Dispensador de Combustible", jPanel2);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pnl_Principal2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIniciarSesion17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIniciarSesion17.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion17.setText("Id de ingreso de combustible");
        jPanel15.add(lblIniciarSesion17, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 220, -1));

        Txt_Id_Ingreso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Id_Ingreso.setForeground(new java.awt.Color(153, 153, 153));
        jPanel15.add(Txt_Id_Ingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 220, -1));

        lblIniciarSesion18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIniciarSesion18.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion18.setText("Id del dispensador");
        jPanel15.add(lblIniciarSesion18, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 147, -1));

        Btn_Registrar_Ingreso_Combustible.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn_Registrar_Ingreso_Combustible.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Registrar_Ingreso_Combustible.setText("Registrar");
        Btn_Registrar_Ingreso_Combustible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Registrar_Ingreso_CombustibleActionPerformed(evt);
            }
        });
        jPanel15.add(Btn_Registrar_Ingreso_Combustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 90, -1));

        Btn_Actualizar_Ingreso_Combustible.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn_Actualizar_Ingreso_Combustible.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Actualizar_Ingreso_Combustible.setText("Actualizar");
        Btn_Actualizar_Ingreso_Combustible.setMaximumSize(new java.awt.Dimension(86, 22));
        Btn_Actualizar_Ingreso_Combustible.setMinimumSize(new java.awt.Dimension(86, 22));
        Btn_Actualizar_Ingreso_Combustible.setPreferredSize(new java.awt.Dimension(86, 22));
        Btn_Actualizar_Ingreso_Combustible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Actualizar_Ingreso_CombustibleActionPerformed(evt);
            }
        });
        jPanel15.add(Btn_Actualizar_Ingreso_Combustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 100, 25));

        lblIniciarSesion21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblIniciarSesion21.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion21.setText("Ingreso de combustible");
        jPanel15.add(lblIniciarSesion21, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, -1, 20));

        lblIniciarSesion22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIniciarSesion22.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion22.setText("Cantidad que ingresa(Litros)");
        jPanel15.add(lblIniciarSesion22, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 200, -1));

        Txt_Ingreso_Litros.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Ingreso_Litros.setForeground(new java.awt.Color(153, 153, 153));
        jPanel15.add(Txt_Ingreso_Litros, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 220, -1));

        lblIniciarSesion31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIniciarSesion31.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion31.setText("Fecha de ingreso");
        jPanel15.add(lblIniciarSesion31, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 147, -1));
        jPanel15.add(DCC_Fecha_Ingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 220, -1));

        Jcb_Disp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Jcb_Disp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion" }));
        jPanel15.add(Jcb_Disp, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 220, -1));

        jPanel11.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 820, 270));

        jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIniciarSesion24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIniciarSesion24.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion24.setText("Id del retiro de combustible");
        jPanel16.add(lblIniciarSesion24, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 220, -1));

        Txt_Id_Dispensador_Combustible.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Id_Dispensador_Combustible.setForeground(new java.awt.Color(153, 153, 153));
        jPanel16.add(Txt_Id_Dispensador_Combustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 220, -1));

        lblIniciarSesion25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIniciarSesion25.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion25.setText("Id del dispensador");
        jPanel16.add(lblIniciarSesion25, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 147, -1));

        lblIniciarSesion26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIniciarSesion26.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion26.setText("Matricula de vehiculo ");
        jPanel16.add(lblIniciarSesion26, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 147, -1));

        Btn_Registrar_Dispensado_Combustible.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn_Registrar_Dispensado_Combustible.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Registrar_Dispensado_Combustible.setText("Registrar");
        Btn_Registrar_Dispensado_Combustible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Registrar_Dispensado_CombustibleActionPerformed(evt);
            }
        });
        jPanel16.add(Btn_Registrar_Dispensado_Combustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 90, -1));

        Btn_Actualizar_Dispensado_Combustible.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn_Actualizar_Dispensado_Combustible.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Actualizar_Dispensado_Combustible.setText("Actualizar");
        Btn_Actualizar_Dispensado_Combustible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Actualizar_Dispensado_CombustibleActionPerformed(evt);
            }
        });
        jPanel16.add(Btn_Actualizar_Dispensado_Combustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 100, -1));

        Jcb_Matricula.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Jcb_Matricula.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion" }));
        jPanel16.add(Jcb_Matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 220, -1));

        lblIniciarSesion28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblIniciarSesion28.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion28.setText("Dispensado de Combustible");
        jPanel16.add(lblIniciarSesion28, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, -1, -1));

        lblIniciarSesion29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIniciarSesion29.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion29.setText("Fecha de salida de combustible");
        jPanel16.add(lblIniciarSesion29, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 200, -1));

        Txt_Kilometraje.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Kilometraje.setForeground(new java.awt.Color(153, 153, 153));
        jPanel16.add(Txt_Kilometraje, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 220, -1));

        lblIniciarSesion30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIniciarSesion30.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion30.setText("Kilometraje");
        jPanel16.add(lblIniciarSesion30, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 147, -1));

        lblIniciarSesion27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIniciarSesion27.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion27.setText("Cantidad que retira(Litros)");
        jPanel16.add(lblIniciarSesion27, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 200, -1));

        Txt_Litros_Retiro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Litros_Retiro.setForeground(new java.awt.Color(153, 153, 153));
        jPanel16.add(Txt_Litros_Retiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 220, -1));
        jPanel16.add(DCC_Fecha_Combustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 220, -1));

        Jcb_Id_Dispensador.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Jcb_Id_Dispensador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion" }));
        jPanel16.add(Jcb_Id_Dispensador, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 220, -1));

        jPanel11.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 370));

        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 650));

        Pnl_Principal2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel9.add(Pnl_Principal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 820, 650));

        jPanel6.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane1.addTab("Dispensado/Ingreso de Combustible", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Default_JCB() throws SQLException {
        Connection_SQL.get_Fuel_Name_In_JCB(Jcb_Gasolina_Tanque);
        Connection_SQL.get_Tank_Id_In_JCB(Jcb_Id_Tanque);
        Connection_SQL.get_Vehicle_Name(Jcb_Matricula);
        Connection_SQL.get_Dispenser_Id(Jcb_Disp);
        Connection_SQL.get_Dispenser_Id(Jcb_Id_Dispensador);

    }

    private void Btn_Actualizar_TanqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Actualizar_TanqueActionPerformed
        try {
            int Id = Integer.parseInt(Txt_Id_Tanque.getText());
            Float Capacity = Float.parseFloat(Txt_Capacidad_Tanque.getText());
            String Fuel = (String) Jcb_Gasolina_Tanque.getSelectedItem();
            int Fuel_Id = Connection_SQL.get_Fuel_Id_By_Name(Fuel);
            String Description = TxA_Descripcion_Tanque.getText();

            Fuel_Tank_Obj Obj = new Fuel_Tank_Obj(Id, Description, Capacity, Fuel_Id, 1);

            int Rows_Affected = CUD_SQL.Update_Fuel_Tank(Obj);
            if (Rows_Affected != 0) {
                Date Current_Date = new Date();
                Binnacle_Obj Binnacle = new Binnacle_Obj("Actualizacion de Tanque", Actual_User, "Seccion de Dispensador", Current_Date);
                Insert_Binnacle_Record(Binnacle);
                Txt_Id_Tanque.setText("");
                Txt_Capacidad_Tanque.setText("");
                Jcb_Gasolina_Tanque.setSelectedItem("Seleccione una opcion");
                TxA_Descripcion_Tanque.setText("");
                Connection_SQL.get_Tank_Id_In_JCB(Jcb_Id_Tanque);
                Connection_SQL.get_Dispenser_Id(Jcb_Disp);
                Connection_SQL.get_Dispenser_Id(Jcb_Id_Dispensador);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Dispenser_Section.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Btn_Actualizar_TanqueActionPerformed

    private void Btn_Registrar_TanqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Registrar_TanqueActionPerformed
        try {
            int Id = Integer.parseInt(Txt_Id_Tanque.getText());
            Float Capacity = Float.parseFloat(Txt_Capacidad_Tanque.getText());
            String Fuel = (String) Jcb_Gasolina_Tanque.getSelectedItem();
            int Fuel_Id = Connection_SQL.get_Fuel_Id_By_Name(Fuel);
            String Description = TxA_Descripcion_Tanque.getText();

            Fuel_Tank_Obj Obj = new Fuel_Tank_Obj(Id, Description, Capacity, Fuel_Id, 1);

            int Rows_Affected = CUD_SQL.Insert_Fuel_Tank(Obj);
            if (Rows_Affected != 0) {
                Date Current_Date = new Date();
                Binnacle_Obj Binnacle = new Binnacle_Obj("Registro de Tanque", Actual_User, "Seccion de Dispensador", Current_Date);
                Insert_Binnacle_Record(Binnacle);
                Txt_Id_Tanque.setText("");
                Txt_Capacidad_Tanque.setText("");
                Jcb_Gasolina_Tanque.setSelectedItem("Seleccione una opcion");
                TxA_Descripcion_Tanque.setText("");
                Connection_SQL.get_Tank_Id_In_JCB(Jcb_Id_Tanque);
                Connection_SQL.get_Dispenser_Id(Jcb_Disp);
                Connection_SQL.get_Dispenser_Id(Jcb_Id_Dispensador);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Dispenser_Section.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_Btn_Registrar_TanqueActionPerformed

    private void Btn_Actualizar_DispensadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Actualizar_DispensadorActionPerformed
        try {
            int Id = Integer.parseInt(Txt_Id_Dispensador.getText());
            int Tank_Id = Integer.parseInt((String) Jcb_Id_Tanque.getSelectedItem());
            String Description = TxA_Descripcion_Dispensador.getText();

            Dispenser_Obj Obj = new Dispenser_Obj(Id, Description, Tank_Id, 1);
            int Rows_Affected = CUD_SQL.Update_Dispenser(Obj);

            if (Rows_Affected != 0) {
                Date Current_Date = new Date();
                Binnacle_Obj Binnacle = new Binnacle_Obj("Actualizacion de Dispensador", Actual_User, "Seccion de Dispensador", Current_Date);
                Insert_Binnacle_Record(Binnacle);
                Txt_Id_Dispensador.setText("");
                Jcb_Id_Tanque.setSelectedItem("Seleccione una opcion");
                TxA_Descripcion_Dispensador.setText("");
            }

        } catch (SQLException ex) {
            Logger.getLogger(Dispenser_Section.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Btn_Actualizar_DispensadorActionPerformed

    private void Btn_Registrar_DispensadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Registrar_DispensadorActionPerformed
        try {
            int Id = Integer.parseInt(Txt_Id_Dispensador.getText());
            int Tank_Id = Integer.parseInt((String) Jcb_Id_Tanque.getSelectedItem());
            String Description = TxA_Descripcion_Dispensador.getText();

            Dispenser_Obj Obj = new Dispenser_Obj(Id, Description, Tank_Id, 1);
            int Rows_Affected = CUD_SQL.Insert_Dispenser(Obj);

            if (Rows_Affected != 0) {
                Date Current_Date = new Date();
                Binnacle_Obj Binnacle = new Binnacle_Obj("Registro de Dispensador", Actual_User, "Seccion de Dispensador", Current_Date);
                Insert_Binnacle_Record(Binnacle);
                Txt_Id_Dispensador.setText("");
                Jcb_Id_Tanque.setSelectedItem("Seleccione una opcion");
                TxA_Descripcion_Dispensador.setText("");
                Connection_SQL.get_Dispenser_Id(Jcb_Disp);
                Connection_SQL.get_Dispenser_Id(Jcb_Id_Dispensador);
            }

        } catch (SQLException ex) {
            Logger.getLogger(Dispenser_Section.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_Btn_Registrar_DispensadorActionPerformed

    // Boton que actualiza los datos de un combustible mediante el id de combustible
    private void Btn_Actualizar_CombustibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Actualizar_CombustibleActionPerformed
        int Fuel_Id = Integer.parseInt(Txt_Id_Combustible.getText());
        String Fuel_Name = Txt_Nombre_Combustible.getText();
        String Type = Txt_Tipo_Combustible.getText();
        float Price = Float.parseFloat(Txt_Precio_Litro.getText());

        Fuel_Obj Fuel = new Fuel_Obj(Fuel_Id, Fuel_Name, Type, Price, 1);
        try {
            int Affected_Rows = CUD_SQL.Update_Fuel(Fuel);
            if (Affected_Rows != 0) {
                Date Current_Date = new Date();
                Binnacle_Obj Binnacle = new Binnacle_Obj("Actualizacion de Combustible", Actual_User, "Seccion de Dispensador", Current_Date);
                Insert_Binnacle_Record(Binnacle);
                Txt_Id_Combustible.setText("");
                Txt_Nombre_Combustible.setText("");
                Txt_Tipo_Combustible.setText("");
                Txt_Precio_Litro.setText("");
                Connection_SQL.get_Dispenser_Id(Jcb_Disp);
                Connection_SQL.get_Dispenser_Id(Jcb_Id_Dispensador);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Dispenser_Section.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Btn_Actualizar_CombustibleActionPerformed

    // Boton que ingresa los datos de un combustible 
    private void Btn_Registro_CombustibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Registro_CombustibleActionPerformed
        int Fuel_Id = Integer.parseInt(Txt_Id_Combustible.getText());
        String Fuel_Name = Txt_Nombre_Combustible.getText();
        String Type = Txt_Tipo_Combustible.getText();
        float Price = Float.parseFloat(Txt_Precio_Litro.getText());

        Fuel_Obj Fuel = new Fuel_Obj(Fuel_Id, Fuel_Name, Type, Price, 1);
        try {
            int Affected_Rows = CUD_SQL.Insert_Fuel(Fuel);
            if (Affected_Rows != 0) {
                Date Current_Date = new Date();
                Binnacle_Obj Binnacle = new Binnacle_Obj("Registro de combustible", Actual_User, "Seccion de Dispensador", Current_Date);
                Insert_Binnacle_Record(Binnacle);
                Txt_Id_Combustible.setText("");
                Txt_Nombre_Combustible.setText("");
                Txt_Tipo_Combustible.setText("");
                Txt_Precio_Litro.setText("");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Dispenser_Section.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Btn_Registro_CombustibleActionPerformed

    private void Btn_Registrar_Ingreso_CombustibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Registrar_Ingreso_CombustibleActionPerformed

        try {
            int Id = Integer.parseInt(Txt_Id_Ingreso.getText());
            int Dispenser_Id = Integer.parseInt((String) Jcb_Disp.getSelectedItem());
            Float Liters = Float.parseFloat(Txt_Ingreso_Litros.getText());
            Date Exit_Date = DCC_Fecha_Ingreso.getSelectedDate().getTime();
            Fuel_Entry_Exit_Obj Obj = new Fuel_Entry_Exit_Obj(Id, "", Dispenser_Id, Liters, 0, Exit_Date, "Entrada de Combustible", 1);

            boolean Updated = CUD_SQL.Add_Fuel_Amount_On_Tank(Dispenser_Id, Liters);

            if (Updated) {
                int Affected_Rows = CUD_SQL.Insert_Fuel_Entry_Exit(Obj);
                if (Affected_Rows != 0) {
                    Date Current_Date = new Date();
                    Binnacle_Obj Binnacle = new Binnacle_Obj("Registro de Ingreso de Combustible al Dispensador", Actual_User, "Seccion de Dispensador", Current_Date);
                    Insert_Binnacle_Record(Binnacle);
                    Txt_Id_Ingreso.setText("");
                    Jcb_Disp.setSelectedItem("Seleccione una opcion");
                    DCC_Fecha_Ingreso.setText("");
                    Txt_Ingreso_Litros.setText("");
                }
            } else {
                JOptionPane.showMessageDialog(null, "No puede exceder la capacidad del tanque del dispensador. Intente de nuevo con una menor cantidad");
                return;
            }

        } catch (SQLException ex) {
            Logger.getLogger(Dispenser_Section.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_Btn_Registrar_Ingreso_CombustibleActionPerformed

    private void Btn_Actualizar_Ingreso_CombustibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Actualizar_Ingreso_CombustibleActionPerformed
        try {
            int Id = Integer.parseInt(Txt_Id_Ingreso.getText());
            int Dispenser_Id = Integer.parseInt((String) Jcb_Disp.getSelectedItem());
            Float Liters = Float.parseFloat(Txt_Ingreso_Litros.getText());
            Date Exit_Date = DCC_Fecha_Ingreso.getSelectedDate().getTime();
            Fuel_Entry_Exit_Obj Obj = new Fuel_Entry_Exit_Obj(Id, "", Dispenser_Id, Liters, 0, Exit_Date, "Entrada de Combustible", 1);

            int Affected_Rows = CUD_SQL.Update_Fuel_Entry_Exit(Obj);

            if (Affected_Rows != 0) {
                Date Current_Date = new Date();
                Binnacle_Obj Binnacle = new Binnacle_Obj("Actualizacion de Ingreso de Combustible al Dispensador", Actual_User, "Seccion de Dispensador", Current_Date);
                Insert_Binnacle_Record(Binnacle);
                Txt_Id_Ingreso.setText("");
                Jcb_Disp.setSelectedItem("Seleccione una opcion");
                DCC_Fecha_Ingreso.setText("");
                Txt_Ingreso_Litros.setText("");

            }
        } catch (SQLException ex) {
            Logger.getLogger(Dispenser_Section.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Btn_Actualizar_Ingreso_CombustibleActionPerformed

    private void Btn_Registrar_Dispensado_CombustibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Registrar_Dispensado_CombustibleActionPerformed
        try {
            int Id_Dispenser_Fuel = Integer.parseInt(Txt_Id_Dispensador_Combustible.getText());
            int Dispenser = Integer.parseInt((String) Jcb_Id_Dispensador.getSelectedItem());
            String License_Plate = (String) Jcb_Matricula.getSelectedItem();
            Date Exit_Date = DCC_Fecha_Combustible.getSelectedDate().getTime();
            double Mileage = Float.parseFloat(Txt_Kilometraje.getText());
            double Liters = Integer.parseInt(Txt_Litros_Retiro.getText());

            double Liters_On_Dispenser = Connection_SQL.get_Fuel_Amount_On_Dispenser(Dispenser);
            if (Liters_On_Dispenser < Liters) {
                JOptionPane.showMessageDialog(null, "No hay esa cantidad de combustible en el dispensador.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            Fuel_Entry_Exit_Obj Obj = new Fuel_Entry_Exit_Obj(Id_Dispenser_Fuel, License_Plate, Dispenser, Liters, Mileage, Exit_Date, "Salida de Combustible", 1);

            int Affected_Rows = CUD_SQL.Insert_Fuel_Entry_Exit(Obj);

            if (Affected_Rows != 0) {

                boolean Updated = CUD_SQL.Update_Fuel_Amount_On_Tank(Dispenser, Liters);

                if (Updated) {
                    Date Current_Date = new Date();
                    Binnacle_Obj Binnacle = new Binnacle_Obj("Registro de Retiro de Combustible del Dispensador", Actual_User, "Seccion de Dispensador", Current_Date);
                    Insert_Binnacle_Record(Binnacle);
                    Txt_Id_Dispensador_Combustible.setText("");
                    Jcb_Id_Dispensador.setSelectedItem("Seleccione una opcion");
                    Jcb_Matricula.setSelectedItem("Seleccione una opcion");
                    DCC_Fecha_Combustible.setText("");
                    Txt_Kilometraje.setText("");
                    Txt_Litros_Retiro.setText("");
                }

            }
        } catch (SQLException ex) {
            Logger.getLogger(Dispenser_Section.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Btn_Registrar_Dispensado_CombustibleActionPerformed

    private void Btn_Actualizar_Dispensado_CombustibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Actualizar_Dispensado_CombustibleActionPerformed
        try {
            int Id_Dispenser_Fuel = Integer.parseInt(Txt_Id_Dispensador_Combustible.getText());
            int Dispenser = Integer.parseInt((String) Jcb_Id_Dispensador.getSelectedItem());
            String License_Plate = (String) Jcb_Matricula.getSelectedItem();
            Date Exit_Date = DCC_Fecha_Combustible.getSelectedDate().getTime();
            Float Mileage = Float.parseFloat(Txt_Kilometraje.getText());
            double Liters = Integer.parseInt(Txt_Litros_Retiro.getText());

            Fuel_Entry_Exit_Obj Obj = new Fuel_Entry_Exit_Obj(Id_Dispenser_Fuel, License_Plate, Dispenser, Liters, Mileage, Exit_Date, "Salida de Combustible", 1);

            int Affected_Rows = CUD_SQL.Update_Fuel_Entry_Exit(Obj);

            if (Affected_Rows != 0) {
                Date Current_Date = new Date();
                Binnacle_Obj Binnacle = new Binnacle_Obj("Actualizacion de Retiro de Combustible del Dispensador", Actual_User, "Seccion de Dispensador", Current_Date);
                Insert_Binnacle_Record(Binnacle);
                Txt_Id_Dispensador_Combustible.setText("");
                Jcb_Id_Dispensador.setSelectedItem("Seleccione una opcion");
                Jcb_Matricula.setSelectedItem("Seleccione una opcion");
                DCC_Fecha_Combustible.setText("");
                Txt_Kilometraje.setText("");
                Txt_Litros_Retiro.setText("");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Dispenser_Section.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Btn_Actualizar_Dispensado_CombustibleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Actualizar_Combustible;
    private javax.swing.JButton Btn_Actualizar_Dispensado_Combustible;
    private javax.swing.JButton Btn_Actualizar_Dispensador;
    private javax.swing.JButton Btn_Actualizar_Ingreso_Combustible;
    private javax.swing.JButton Btn_Actualizar_Tanque;
    private javax.swing.JButton Btn_Registrar_Dispensado_Combustible;
    private javax.swing.JButton Btn_Registrar_Dispensador;
    private javax.swing.JButton Btn_Registrar_Ingreso_Combustible;
    private javax.swing.JButton Btn_Registrar_Tanque;
    private javax.swing.JButton Btn_Registro_Combustible;
    private datechooser.beans.DateChooserCombo DCC_Fecha_Combustible;
    private datechooser.beans.DateChooserCombo DCC_Fecha_Ingreso;
    private javax.swing.JComboBox<String> Jcb_Disp;
    private javax.swing.JComboBox<String> Jcb_Gasolina_Tanque;
    private javax.swing.JComboBox<String> Jcb_Id_Dispensador;
    private javax.swing.JComboBox<String> Jcb_Id_Tanque;
    private javax.swing.JComboBox<String> Jcb_Matricula;
    private javax.swing.JPanel Pnl_Principal;
    private javax.swing.JPanel Pnl_Principal1;
    private javax.swing.JPanel Pnl_Principal2;
    private javax.swing.JTextArea TxA_Descripcion_Dispensador;
    private javax.swing.JTextArea TxA_Descripcion_Tanque;
    private javax.swing.JTextField Txt_Capacidad_Tanque;
    private javax.swing.JTextField Txt_Id_Combustible;
    private javax.swing.JTextField Txt_Id_Dispensador;
    private javax.swing.JTextField Txt_Id_Dispensador_Combustible;
    private javax.swing.JTextField Txt_Id_Ingreso;
    private javax.swing.JTextField Txt_Id_Tanque;
    private javax.swing.JTextField Txt_Ingreso_Litros;
    private javax.swing.JTextField Txt_Kilometraje;
    private javax.swing.JTextField Txt_Litros_Retiro;
    private javax.swing.JTextField Txt_Nombre_Combustible;
    private javax.swing.JTextField Txt_Precio_Litro;
    private javax.swing.JTextField Txt_Tipo_Combustible;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblContrasena1;
    private javax.swing.JLabel lblContrasena2;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblIniciarSesion;
    private javax.swing.JLabel lblIniciarSesion10;
    private javax.swing.JLabel lblIniciarSesion11;
    private javax.swing.JLabel lblIniciarSesion12;
    private javax.swing.JLabel lblIniciarSesion13;
    private javax.swing.JLabel lblIniciarSesion17;
    private javax.swing.JLabel lblIniciarSesion18;
    private javax.swing.JLabel lblIniciarSesion21;
    private javax.swing.JLabel lblIniciarSesion22;
    private javax.swing.JLabel lblIniciarSesion24;
    private javax.swing.JLabel lblIniciarSesion25;
    private javax.swing.JLabel lblIniciarSesion26;
    private javax.swing.JLabel lblIniciarSesion27;
    private javax.swing.JLabel lblIniciarSesion28;
    private javax.swing.JLabel lblIniciarSesion29;
    private javax.swing.JLabel lblIniciarSesion30;
    private javax.swing.JLabel lblIniciarSesion31;
    private javax.swing.JLabel lblIniciarSesion4;
    private javax.swing.JLabel lblIniciarSesion5;
    private javax.swing.JLabel lblIniciarSesion7;
    private javax.swing.JLabel lblIniciarSesion8;
    private javax.swing.JLabel lblIniciarSesion9;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuario2;
    // End of variables declaration//GEN-END:variables
}
