/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentation;

import Data.CUD_SQL;
import Data.Connection_SQL;
import Data.Details_Obj;
import Data.Header_Obj;
import Data.Maintenance_Assigments_Obj;
import Data.Maintenance_Type_Obj;
import Data.Part_Obj;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Mechanics_Section extends javax.swing.JPanel {

    /**
     * Creates new form Mechanic
     */
    public Mechanics_Section() throws SQLException {
        initComponents();
        Connection_SQL.get_Vehicle_Name(Jcb_Vehiculo);
        Actions_Listeners_Method();
    }

    // Metodo que contiene a Action Listeners
    private void Actions_Listeners_Method() {
        Jcb_Vehiculo.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                String Selected_License_Plate = (String) Jcb_Vehiculo.getSelectedItem();
                try {
                    int Vehicle_Id = Connection_SQL.get_Vehicle_Id_By_Name(Selected_License_Plate);
                    Lbl_Actualizar_Id.setText(String.valueOf(Vehicle_Id));
                } catch (SQLException ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Error al obtener el ID del vehículo.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        Txt_Nombre_Pieza = new javax.swing.JTextField();
        Btn_Registro_Pieza = new javax.swing.JButton();
        lblContrasena2 = new javax.swing.JLabel();
        lblContrasena1 = new javax.swing.JLabel();
        lblUsuario2 = new javax.swing.JLabel();
        Txt_Compatibilidad = new javax.swing.JTextField();
        Btn_Actualizar_Pieza = new javax.swing.JButton();
        Txt_Categoria_Pieza = new javax.swing.JTextField();
        Txt_Manufactura = new javax.swing.JTextField();
        Txt_Garantia = new javax.swing.JTextField();
        lblContrasena3 = new javax.swing.JLabel();
        Txt_Precio_Unidad = new javax.swing.JTextField();
        lblContrasena4 = new javax.swing.JLabel();
        lblIniciarSesion = new javax.swing.JLabel();
        lblUsuario1 = new javax.swing.JLabel();
        Txt_Id = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        lblIniciarSesion1 = new javax.swing.JLabel();
        Jcb_Matricula_Asignacion = new javax.swing.JComboBox<>();
        lblIniciarSesion28 = new javax.swing.JLabel();
        Jcb_Id_Mantenimiento = new javax.swing.JComboBox<>();
        lblIniciarSesion30 = new javax.swing.JLabel();
        Jcb_Nombre_Pieza_Asignacipn = new javax.swing.JComboBox<>();
        lblIniciarSesion31 = new javax.swing.JLabel();
        Txt_Frecuencia_Dias = new javax.swing.JTextField();
        lblIniciarSesion32 = new javax.swing.JLabel();
        Txt_Kilometraje = new javax.swing.JTextField();
        lblIniciarSesion33 = new javax.swing.JLabel();
        Btn_Actualizar_Asignacion_Mantenimiento = new javax.swing.JButton();
        Btn_Registrar_Asignacion_Mantenimiento = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        lblIniciarSesion3 = new javax.swing.JLabel();
        lblIniciarSesion11 = new javax.swing.JLabel();
        lblIniciarSesion12 = new javax.swing.JLabel();
        Txt_Id_Boleta = new javax.swing.JTextField();
        lblIniciarSesion14 = new javax.swing.JLabel();
        Jcb_Matricula_Boleta = new javax.swing.JComboBox<>();
        lblIniciarSesion15 = new javax.swing.JLabel();
        lblIniciarSesion16 = new javax.swing.JLabel();
        Txt_Kilometraje_Boleta = new javax.swing.JTextField();
        lblIniciarSesion17 = new javax.swing.JLabel();
        Btn_Registrar_Boleta_Mantenimiento = new javax.swing.JButton();
        Btn_Actualizar_Boleta_Mantenimiento = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblIniciarSesion18 = new javax.swing.JLabel();
        lblIniciarSesion19 = new javax.swing.JLabel();
        Txt_Id_Detalle = new javax.swing.JTextField();
        lblIniciarSesion20 = new javax.swing.JLabel();
        lblIniciarSesion21 = new javax.swing.JLabel();
        Jcb_Id_Boleta = new javax.swing.JComboBox<>();
        Jcb_Nombre_Pieza = new javax.swing.JComboBox<>();
        Jcb_Tipo_Mantenimiento_Detalle = new javax.swing.JComboBox<>();
        lblIniciarSesion22 = new javax.swing.JLabel();
        Btn_Registrar_Detalle_Mantenimiento = new javax.swing.JButton();
        Btn_Actualizar_Detalle_Mantenimiento = new javax.swing.JButton();
        DCC_Fecha = new datechooser.beans.DateChooserCombo();
        Jcb_Chofer = new javax.swing.JComboBox<>();
        Jcb_Mecanico = new javax.swing.JComboBox<>();
        jPanel11 = new javax.swing.JPanel();
        lblIniciarSesion2 = new javax.swing.JLabel();
        lblIniciarSesion4 = new javax.swing.JLabel();
        Txt_Id_Mantenimiento = new javax.swing.JTextField();
        Txt_Tipo_Mantenimiento = new javax.swing.JTextField();
        lblIniciarSesion6 = new javax.swing.JLabel();
        Txt_Frecuencia = new javax.swing.JTextField();
        lblIniciarSesion7 = new javax.swing.JLabel();
        Txt_Costo_Estimado = new javax.swing.JTextField();
        lblIniciarSesion8 = new javax.swing.JLabel();
        lblIniciarSesion9 = new javax.swing.JLabel();
        lblIniciarSesion10 = new javax.swing.JLabel();
        Lbl_Actualizar_Id = new javax.swing.JLabel();
        Jcb_Vehiculo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxA_Descripcion = new javax.swing.JTextArea();
        lblIniciarSesion5 = new javax.swing.JLabel();
        Btn_Registrar_Mantenimiento = new javax.swing.JButton();
        Btn_Actualizar_Mantenimiento = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario.setText("Nombre de la pieza");
        jPanel2.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, -1));

        Txt_Nombre_Pieza.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Nombre_Pieza.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(Txt_Nombre_Pieza, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 350, 40));

        Btn_Registro_Pieza.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_Registro_Pieza.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Registro_Pieza.setText("Registrar");
        Btn_Registro_Pieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Registro_PiezaActionPerformed(evt);
            }
        });
        jPanel2.add(Btn_Registro_Pieza, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 620, -1, -1));

        lblContrasena2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblContrasena2.setForeground(new java.awt.Color(0, 0, 0));
        lblContrasena2.setText("Manufactura");
        jPanel2.add(lblContrasena2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 220, -1));

        lblContrasena1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblContrasena1.setForeground(new java.awt.Color(0, 0, 0));
        lblContrasena1.setText("Compatibilidad(X Vehiculo)(Opcional)");
        jPanel2.add(lblContrasena1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 270, -1));

        lblUsuario2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsuario2.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario2.setText("Categoria de la pieza");
        jPanel2.add(lblUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, -1));

        Txt_Compatibilidad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Compatibilidad.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(Txt_Compatibilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 350, 40));

        Btn_Actualizar_Pieza.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_Actualizar_Pieza.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Actualizar_Pieza.setText("Actualizar");
        Btn_Actualizar_Pieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Actualizar_PiezaActionPerformed(evt);
            }
        });
        jPanel2.add(Btn_Actualizar_Pieza, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 620, 120, -1));

        Txt_Categoria_Pieza.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Categoria_Pieza.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(Txt_Categoria_Pieza, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 350, 40));

        Txt_Manufactura.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Manufactura.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(Txt_Manufactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 350, 40));

        Txt_Garantia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Garantia.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(Txt_Garantia, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, 350, 40));

        lblContrasena3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblContrasena3.setForeground(new java.awt.Color(0, 0, 0));
        lblContrasena3.setText("Periodo de garantía(Si no tiene coloque 0)(Meses)");
        jPanel2.add(lblContrasena3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 350, -1));

        Txt_Precio_Unidad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Precio_Unidad.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(Txt_Precio_Unidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 560, 350, 40));

        lblContrasena4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblContrasena4.setForeground(new java.awt.Color(0, 0, 0));
        lblContrasena4.setText("Precio por unidad");
        jPanel2.add(lblContrasena4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, 210, -1));

        lblIniciarSesion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblIniciarSesion.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion.setText("Registro de Equipo/Piezas");
        jPanel2.add(lblIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 260, 40));

        lblUsuario1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsuario1.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario1.setText("Id de la pieza");
        jPanel2.add(lblUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        Txt_Id.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Id.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(Txt_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 350, 40));

        jTabbedPane1.addTab("Partes de Equipos", jPanel2);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblIniciarSesion1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblIniciarSesion1.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion1.setText("Asignación de Mantenimientos");

        Jcb_Matricula_Asignacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Jcb_Matricula_Asignacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una matricula:" }));

        lblIniciarSesion28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIniciarSesion28.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion28.setText("Matricula del vehiculo");

        Jcb_Id_Mantenimiento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Jcb_Id_Mantenimiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el mantenimiento", " ", " " }));

        lblIniciarSesion30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIniciarSesion30.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion30.setText("Tipo de mantenimiento");

        Jcb_Nombre_Pieza_Asignacipn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Jcb_Nombre_Pieza_Asignacipn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la pieza" }));

        lblIniciarSesion31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIniciarSesion31.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion31.setText("Nombre de la pieza");

        Txt_Frecuencia_Dias.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Frecuencia_Dias.setForeground(new java.awt.Color(153, 153, 153));

        lblIniciarSesion32.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIniciarSesion32.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion32.setText("Frecuencia(Dias)");

        Txt_Kilometraje.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Kilometraje.setForeground(new java.awt.Color(153, 153, 153));

        lblIniciarSesion33.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIniciarSesion33.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion33.setText("Kilometraje");

        Btn_Actualizar_Asignacion_Mantenimiento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn_Actualizar_Asignacion_Mantenimiento.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Actualizar_Asignacion_Mantenimiento.setText("Actualizar");
        Btn_Actualizar_Asignacion_Mantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Actualizar_Asignacion_MantenimientoActionPerformed(evt);
            }
        });

        Btn_Registrar_Asignacion_Mantenimiento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn_Registrar_Asignacion_Mantenimiento.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Registrar_Asignacion_Mantenimiento.setText("Registrar");
        Btn_Registrar_Asignacion_Mantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Registrar_Asignacion_MantenimientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(Jcb_Matricula_Asignacion, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(lblIniciarSesion28, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)))
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Jcb_Id_Mantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(lblIniciarSesion30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIniciarSesion31, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jcb_Nombre_Pieza_Asignacipn, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(lblIniciarSesion1)
                        .addGap(275, 275, 275))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Txt_Frecuencia_Dias, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(lblIniciarSesion32, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)))
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(Txt_Kilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(lblIniciarSesion33, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(153, 153, 153))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(Btn_Registrar_Asignacion_Mantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_Actualizar_Asignacion_Mantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(273, 273, 273))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(lblIniciarSesion1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(lblIniciarSesion31)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIniciarSesion30, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIniciarSesion28, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Jcb_Id_Mantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jcb_Nombre_Pieza_Asignacipn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jcb_Matricula_Asignacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIniciarSesion33)
                            .addComponent(lblIniciarSesion32))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Txt_Kilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(Txt_Frecuencia_Dias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Registrar_Asignacion_Mantenimiento)
                    .addComponent(Btn_Actualizar_Asignacion_Mantenimiento))
                .addGap(70, 70, 70))
        );

        jPanel6.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 436, 810, 210));

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblIniciarSesion3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblIniciarSesion3.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion3.setText("Boletas de Mantenimientos");

        lblIniciarSesion11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIniciarSesion11.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion11.setText("Nombre del mecanico");

        lblIniciarSesion12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIniciarSesion12.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion12.setText("Fecha");

        Txt_Id_Boleta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Id_Boleta.setForeground(new java.awt.Color(153, 153, 153));

        lblIniciarSesion14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIniciarSesion14.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion14.setText("Id de Boleta");

        Jcb_Matricula_Boleta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Jcb_Matricula_Boleta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una matricula:" }));

        lblIniciarSesion15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIniciarSesion15.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion15.setText("Matricula del vehiculo");

        lblIniciarSesion16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIniciarSesion16.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion16.setText("Nombre del chofer");

        Txt_Kilometraje_Boleta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Kilometraje_Boleta.setForeground(new java.awt.Color(153, 153, 153));

        lblIniciarSesion17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIniciarSesion17.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion17.setText("Kilometraje");

        Btn_Registrar_Boleta_Mantenimiento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn_Registrar_Boleta_Mantenimiento.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Registrar_Boleta_Mantenimiento.setText("Registrar");
        Btn_Registrar_Boleta_Mantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Registrar_Boleta_MantenimientoActionPerformed(evt);
            }
        });

        Btn_Actualizar_Boleta_Mantenimiento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn_Actualizar_Boleta_Mantenimiento.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Actualizar_Boleta_Mantenimiento.setText("Actualizar");
        Btn_Actualizar_Boleta_Mantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Actualizar_Boleta_MantenimientoActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblIniciarSesion18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblIniciarSesion18.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion18.setText("Detalles");

        lblIniciarSesion19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIniciarSesion19.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion19.setText("Id de Detalle");

        Txt_Id_Detalle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Id_Detalle.setForeground(new java.awt.Color(153, 153, 153));

        lblIniciarSesion20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIniciarSesion20.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion20.setText("Id de boleta");

        lblIniciarSesion21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIniciarSesion21.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion21.setText("Nombre de la pieza");

        Jcb_Id_Boleta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Jcb_Id_Boleta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la boleta:" }));

        Jcb_Nombre_Pieza.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Jcb_Nombre_Pieza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la pieza" }));

        Jcb_Tipo_Mantenimiento_Detalle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Jcb_Tipo_Mantenimiento_Detalle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el mantenimiento", " ", " " }));

        lblIniciarSesion22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIniciarSesion22.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion22.setText("Tipo de mantenimiento");

        Btn_Registrar_Detalle_Mantenimiento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn_Registrar_Detalle_Mantenimiento.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Registrar_Detalle_Mantenimiento.setText("Registrar");
        Btn_Registrar_Detalle_Mantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Registrar_Detalle_MantenimientoActionPerformed(evt);
            }
        });

        Btn_Actualizar_Detalle_Mantenimiento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn_Actualizar_Detalle_Mantenimiento.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Actualizar_Detalle_Mantenimiento.setText("Actualizar");
        Btn_Actualizar_Detalle_Mantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Actualizar_Detalle_MantenimientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIniciarSesion18, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIniciarSesion20, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jcb_Id_Boleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIniciarSesion21, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(Btn_Registrar_Detalle_Mantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Btn_Actualizar_Detalle_Mantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Txt_Id_Detalle, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIniciarSesion19, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jcb_Tipo_Mantenimiento_Detalle, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblIniciarSesion22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Jcb_Nombre_Pieza, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(lblIniciarSesion18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIniciarSesion19)
                    .addComponent(lblIniciarSesion22, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Jcb_Tipo_Mantenimiento_Detalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_Id_Detalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIniciarSesion20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jcb_Id_Boleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIniciarSesion21)
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn_Registrar_Detalle_Mantenimiento)
                            .addComponent(Btn_Actualizar_Detalle_Mantenimiento))
                        .addGap(34, 34, 34)))
                .addComponent(Jcb_Nombre_Pieza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        Jcb_Chofer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Jcb_Chofer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un chofer:" }));

        Jcb_Mecanico.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Jcb_Mecanico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un mecanico:" }));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(319, Short.MAX_VALUE)
                .addComponent(lblIniciarSesion3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(295, 295, 295))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIniciarSesion15, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIniciarSesion14, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIniciarSesion12, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIniciarSesion11, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jcb_Matricula_Boleta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Txt_Id_Boleta)
                    .addComponent(DCC_Fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Jcb_Mecanico, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIniciarSesion16, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIniciarSesion17, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_Kilometraje_Boleta, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(Btn_Registrar_Boleta_Mantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_Actualizar_Boleta_Mantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Jcb_Chofer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(lblIniciarSesion3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(lblIniciarSesion14)
                                .addGap(1, 1, 1)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Txt_Id_Boleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Jcb_Chofer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4)
                                .addComponent(lblIniciarSesion15, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Jcb_Matricula_Boleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(lblIniciarSesion16)
                                .addGap(28, 28, 28)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(Txt_Kilometraje_Boleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblIniciarSesion17))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIniciarSesion12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DCC_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Btn_Registrar_Boleta_Mantenimiento)
                                    .addComponent(Btn_Actualizar_Boleta_Mantenimiento)))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(lblIniciarSesion11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Jcb_Mecanico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 1, 1))
        );

        jPanel6.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 216, 810, -1));

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIniciarSesion2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblIniciarSesion2.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion2.setText("Tipos de Mantenimientos");
        jPanel11.add(lblIniciarSesion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 1, -1, -1));

        lblIniciarSesion4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIniciarSesion4.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion4.setText("Id del Mantenimiento");
        jPanel11.add(lblIniciarSesion4, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 19, 147, -1));

        Txt_Id_Mantenimiento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Id_Mantenimiento.setForeground(new java.awt.Color(153, 153, 153));
        jPanel11.add(Txt_Id_Mantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 35, 147, -1));

        Txt_Tipo_Mantenimiento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Tipo_Mantenimiento.setForeground(new java.awt.Color(153, 153, 153));
        jPanel11.add(Txt_Tipo_Mantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 83, 147, -1));

        lblIniciarSesion6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIniciarSesion6.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion6.setText("Tipo de Mantenimiento");
        jPanel11.add(lblIniciarSesion6, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 62, 147, -1));

        Txt_Frecuencia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Frecuencia.setForeground(new java.awt.Color(153, 153, 153));
        jPanel11.add(Txt_Frecuencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 131, 147, -1));

        lblIniciarSesion7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIniciarSesion7.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion7.setText("Frecuencia(Dias)");
        jPanel11.add(lblIniciarSesion7, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 110, 147, -1));

        Txt_Costo_Estimado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Costo_Estimado.setForeground(new java.awt.Color(153, 153, 153));
        jPanel11.add(Txt_Costo_Estimado, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 179, 147, -1));

        lblIniciarSesion8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIniciarSesion8.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion8.setText("Costos estimados");
        jPanel11.add(lblIniciarSesion8, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 158, 147, -1));

        lblIniciarSesion9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIniciarSesion9.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion9.setText("Matricula del vehiculo");
        jPanel11.add(lblIniciarSesion9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 147, -1));

        lblIniciarSesion10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIniciarSesion10.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion10.setText("Id:");
        jPanel11.add(lblIniciarSesion10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 31, -1));

        Lbl_Actualizar_Id.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Lbl_Actualizar_Id.setForeground(new java.awt.Color(0, 0, 0));
        Lbl_Actualizar_Id.setText("0");
        jPanel11.add(Lbl_Actualizar_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 65, 21));

        Jcb_Vehiculo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Jcb_Vehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una matricula:" }));
        jPanel11.add(Jcb_Vehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 190, -1));

        TxA_Descripcion.setColumns(20);
        TxA_Descripcion.setRows(5);
        jScrollPane1.setViewportView(TxA_Descripcion);

        jPanel11.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 36, 360, 164));

        lblIniciarSesion5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIniciarSesion5.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion5.setText("Descripción");
        jPanel11.add(lblIniciarSesion5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 19, 79, -1));

        Btn_Registrar_Mantenimiento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn_Registrar_Mantenimiento.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Registrar_Mantenimiento.setText("Registrar");
        Btn_Registrar_Mantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Registrar_MantenimientoActionPerformed(evt);
            }
        });
        jPanel11.add(Btn_Registrar_Mantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 90, -1));

        Btn_Actualizar_Mantenimiento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn_Actualizar_Mantenimiento.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Actualizar_Mantenimiento.setText("Actualizar");
        Btn_Actualizar_Mantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Actualizar_MantenimientoActionPerformed(evt);
            }
        });
        jPanel11.add(Btn_Actualizar_Mantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, 100, -1));

        jPanel6.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 810, 210));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 760));

        jTabbedPane1.addTab("Mantenimientos", jPanel1);

        add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 690));
    }// </editor-fold>//GEN-END:initComponents

    // Boton que actualiza la informacion de una pieza de vehiculo mediante el id
    private void Btn_Actualizar_PiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Actualizar_PiezaActionPerformed
        try {
            int Part_Id = Integer.parseInt(Txt_Id.getText());
            String Part_Name = Txt_Nombre_Pieza.getText();
            String Part_Category = Txt_Categoria_Pieza.getText();
            String Manufacture = Txt_Manufactura.getText();
            String Compatiility = Txt_Compatibilidad.getText();
            int Warrantly = Integer.parseInt(Txt_Garantia.getText());
            float Price = Float.parseFloat(Txt_Precio_Unidad.getText());

            Part_Obj Obj = new Part_Obj(Part_Id, Part_Name, Part_Category, Manufacture, Compatiility, Warrantly, Price, 1);

            int Rows_Affected = CUD_SQL.Update_Part(Obj);

            if (Rows_Affected != 0) {
                Txt_Id.setText("");
                Txt_Nombre_Pieza.setText("");
                Txt_Categoria_Pieza.setText("");
                Txt_Manufactura.setText("");
                Txt_Compatibilidad.setText("");
                Txt_Garantia.setText("");
                Txt_Precio_Unidad.setText("");
            }

        } catch (SQLException ex) {
            Logger.getLogger(Mechanics_Section.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Btn_Actualizar_PiezaActionPerformed
    // Boton que ingresa la informacion de una pieza de vehiculo
    private void Btn_Registro_PiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Registro_PiezaActionPerformed
        try {
            int Part_Id = Integer.parseInt(Txt_Id.getText());
            String Part_Name = Txt_Nombre_Pieza.getText();
            String Part_Category = Txt_Categoria_Pieza.getText();
            String Manufacture = Txt_Manufactura.getText();
            String Compatiility = Txt_Compatibilidad.getText();
            int Warrantly = Integer.parseInt(Txt_Garantia.getText());
            float Price = Float.parseFloat(Txt_Precio_Unidad.getText());

            Part_Obj Obj = new Part_Obj(Part_Id, Part_Name, Part_Category, Manufacture, Compatiility, Warrantly, Price, 1);

            int Rows_Affected = CUD_SQL.Insert_Part(Obj);

            if (Rows_Affected != 0) {
                Txt_Id.setText("");
                Txt_Nombre_Pieza.setText("");
                Txt_Categoria_Pieza.setText("");
                Txt_Manufactura.setText("");
                Txt_Compatibilidad.setText("");
                Txt_Garantia.setText("");
                Txt_Precio_Unidad.setText("");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Mechanics_Section.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Btn_Registro_PiezaActionPerformed
    // Boton que ingresa la informacion del tipo de mantenimiento vehicular
    private void Btn_Registrar_MantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Registrar_MantenimientoActionPerformed
        int Maintenance_Id = Integer.parseInt(Txt_Id_Mantenimiento.getText());
        String Maintenance_Type = Txt_Tipo_Mantenimiento.getText();
        String Description = TxA_Descripcion.getText();
        String Frequency = Txt_Frecuencia.getText();
        float Approximate_Cost = Float.parseFloat(Txt_Costo_Estimado.getText());
        String License_Plate = (String) Jcb_Vehiculo.getSelectedItem();
        try {
            int Vehicle_Id = Connection_SQL.get_Vehicle_Id_By_Name(License_Plate);
            Maintenance_Type_Obj Obj = new Maintenance_Type_Obj(Maintenance_Id, Maintenance_Type, Description, Frequency, Approximate_Cost, Vehicle_Id, 1);
            int Rows_Affected = CUD_SQL.Insert_Maintenance_Type(Obj);
            if (Rows_Affected != 0) {
                Txt_Id.setText("");
                Txt_Tipo_Mantenimiento.setText("");
                Txt_Frecuencia.setText("");
                Txt_Costo_Estimado.setText("");
                TxA_Descripcion.setText("");
                Jcb_Vehiculo.setSelectedItem("Seleccione una matricula:");
            }

        } catch (SQLException ex) {
            Logger.getLogger(Mechanics_Section.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Btn_Registrar_MantenimientoActionPerformed
    // Boton que actualiza la informacion del tipo de mantenimiento vehicular
    private void Btn_Actualizar_MantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Actualizar_MantenimientoActionPerformed
        int Maintenance_Id = Integer.parseInt(Txt_Id_Mantenimiento.getText());
        String Maintenance_Type = Txt_Tipo_Mantenimiento.getText();
        String Description = TxA_Descripcion.getText();
        String Frequency = Txt_Frecuencia.getText();
        float Approximate_Cost = Float.parseFloat(Txt_Costo_Estimado.getText());
        String License_Plate = (String) Jcb_Vehiculo.getSelectedItem();
        try {
            int Vehicle_Id = Connection_SQL.get_Vehicle_Id_By_Name(License_Plate);
            Maintenance_Type_Obj Obj = new Maintenance_Type_Obj(Maintenance_Id, Maintenance_Type, Description, Frequency, Approximate_Cost, Vehicle_Id, 1);
            int Rows_Affected = CUD_SQL.Update_Maintenance_Type(Obj);
            if (Rows_Affected != 0) {
                Txt_Id.setText("");
                Txt_Tipo_Mantenimiento.setText("");
                Txt_Frecuencia.setText("");
                Txt_Costo_Estimado.setText("");
                TxA_Descripcion.setText("");
                Jcb_Vehiculo.setSelectedItem("Seleccione una matricula:");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Mechanics_Section.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Btn_Actualizar_MantenimientoActionPerformed

    private void Btn_Registrar_Boleta_MantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Registrar_Boleta_MantenimientoActionPerformed

        try {

            int Id = Integer.parseInt(Txt_Id_Boleta.getText());
            String License_Plate = (String) Jcb_Matricula_Boleta.getSelectedItem();
            Date Date = DCC_Fecha.getSelectedDate().getTime();
            String Driver = (String) Jcb_Chofer.getSelectedItem();
            String Mechanic = (String) Jcb_Mecanico.getSelectedItem();
            double Mileage = Float.parseFloat(Txt_Kilometraje_Boleta.getText());

            Header_Obj Obj = new Header_Obj(Id, License_Plate, Date, Mechanic, Driver, Mileage);

            int Affected_Rows;
            Affected_Rows = CUD_SQL.Insert_Header(Obj);
            if (Affected_Rows != 0) {
                Txt_Id_Boleta.setText("");
                Jcb_Matricula_Boleta.setSelectedItem("Seleccione una matricula:");

                Jcb_Chofer.setSelectedItem("Seleccione un chofer:");
                Jcb_Mecanico.setSelectedItem("Seleccione un mecanico:");
                Txt_Kilometraje_Boleta.setText("");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Mechanics_Section.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_Btn_Registrar_Boleta_MantenimientoActionPerformed

    private void Btn_Actualizar_Boleta_MantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Actualizar_Boleta_MantenimientoActionPerformed
        try {

            int Id = Integer.parseInt(Txt_Id_Boleta.getText());
            String License_Plate = (String) Jcb_Matricula_Boleta.getSelectedItem();
            Date Date = DCC_Fecha.getSelectedDate().getTime();
            String Driver = (String) Jcb_Chofer.getSelectedItem();
            String Mechanic = (String) Jcb_Mecanico.getSelectedItem();
            double Mileage = Float.parseFloat(Txt_Kilometraje_Boleta.getText());

            Header_Obj Obj = new Header_Obj(Id, License_Plate, Date, Mechanic, Driver, Mileage);

            int Affected_Rows;
            Affected_Rows = CUD_SQL.Update_Header(Obj);
            if (Affected_Rows != 0) {
                Txt_Id_Boleta.setText("");
                Jcb_Matricula_Boleta.setSelectedItem("Seleccione una matricula:");

                Jcb_Chofer.setSelectedItem("Seleccione un chofer:");
                Jcb_Mecanico.setSelectedItem("Seleccione un mecanico:");
                Txt_Kilometraje_Boleta.setText("");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Mechanics_Section.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Btn_Actualizar_Boleta_MantenimientoActionPerformed

    private void Btn_Registrar_Detalle_MantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Registrar_Detalle_MantenimientoActionPerformed
        try {
            int Detail_Id = Integer.parseInt(Txt_Id_Detalle.getText());
            int Ticket_Id = (int) Jcb_Id_Boleta.getSelectedItem();
            String Part_Name = (String) Jcb_Nombre_Pieza.getSelectedItem();
            int Part_Id = Connection_SQL.get_Part_Id_By_Name(Part_Name);
            String Maintenance_Type = (String) Jcb_Nombre_Pieza.getSelectedItem();
            int Maintenance_Type_Id = Connection_SQL.get_Maintenance_Type_Id_By_Name(Maintenance_Type);

            Details_Obj Obj = new Details_Obj(Detail_Id, Part_Id, Part_Id, Maintenance_Type_Id);

            int Affected_Rows;
            Affected_Rows = CUD_SQL.Insert_Details(Obj);
            if (Affected_Rows != 0) {
                Txt_Id_Detalle.setText("");
                Jcb_Id_Boleta.setSelectedItem("Seleccione la boleta:");
                Jcb_Nombre_Pieza.setSelectedItem("Seleccione la pieza");
                Jcb_Nombre_Pieza.setSelectedItem("Seleccione el mantenimiento");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Mechanics_Section.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Btn_Registrar_Detalle_MantenimientoActionPerformed

    private void Btn_Actualizar_Detalle_MantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Actualizar_Detalle_MantenimientoActionPerformed
        try {
            int Detail_Id = Integer.parseInt(Txt_Id_Detalle.getText());
            int Ticket_Id = (int) Jcb_Id_Boleta.getSelectedItem();
            String Part_Name = (String) Jcb_Nombre_Pieza.getSelectedItem();
            int Part_Id = Connection_SQL.get_Part_Id_By_Name(Part_Name);
            String Maintenance_Type = (String) Jcb_Nombre_Pieza.getSelectedItem();
            int Maintenance_Type_Id = Connection_SQL.get_Maintenance_Type_Id_By_Name(Maintenance_Type);

            Details_Obj Obj = new Details_Obj(Detail_Id, Part_Id, Part_Id, Maintenance_Type_Id);

            int Affected_Rows;
            Affected_Rows = CUD_SQL.Update_Details(Obj);
            if (Affected_Rows != 0) {
                Txt_Id_Detalle.setText("");
                Jcb_Id_Boleta.setSelectedItem("Seleccione la boleta:");
                Jcb_Nombre_Pieza.setSelectedItem("Seleccione la pieza");
                Jcb_Nombre_Pieza.setSelectedItem("Seleccione el mantenimiento");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Mechanics_Section.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Btn_Actualizar_Detalle_MantenimientoActionPerformed

    private void Btn_Registrar_Asignacion_MantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Registrar_Asignacion_MantenimientoActionPerformed

        try {
            String License_Plate = (String) Jcb_Matricula_Asignacion.getSelectedItem();
            String Part_Name = (String) Jcb_Nombre_Pieza_Asignacipn.getSelectedItem();
            int Part_Id = Connection_SQL.get_Part_Id_By_Name(Part_Name);
            String Maintenance_Type = (String) Jcb_Id_Mantenimiento.getSelectedItem();
            int Maintenance_Type_Id = Connection_SQL.get_Maintenance_Type_Id_By_Name(Maintenance_Type);
            int Frecuency = Integer.parseInt(Txt_Frecuencia_Dias.getText());
            double Mileage = Double.parseDouble(Txt_Kilometraje.getText());

            Maintenance_Assigments_Obj Obj = new Maintenance_Assigments_Obj(License_Plate, Maintenance_Type_Id, Part_Id, Frecuency, Mileage);
            int Affected_Rows;
            Affected_Rows = CUD_SQL.Insert_Maintenance_Assigments(Obj);
            if (Affected_Rows != 0) {
                Txt_Frecuencia_Dias.setText("");
                Txt_Kilometraje.setText("");
                Jcb_Matricula_Asignacion.setSelectedItem("Seleccione la matricula:");
                Jcb_Nombre_Pieza_Asignacipn.setSelectedItem("Seleccione la pieza");
                Jcb_Id_Mantenimiento.setSelectedItem("Seleccione el mantenimiento");
            }

        } catch (SQLException ex) {
            Logger.getLogger(Mechanics_Section.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Btn_Registrar_Asignacion_MantenimientoActionPerformed

    private void Btn_Actualizar_Asignacion_MantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Actualizar_Asignacion_MantenimientoActionPerformed
        try {
            String License_Plate = (String) Jcb_Matricula_Asignacion.getSelectedItem();
            String Part_Name = (String) Jcb_Nombre_Pieza_Asignacipn.getSelectedItem();
            int Part_Id = Connection_SQL.get_Part_Id_By_Name(Part_Name);
            String Maintenance_Type = (String) Jcb_Id_Mantenimiento.getSelectedItem();
            int Maintenance_Type_Id = Connection_SQL.get_Maintenance_Type_Id_By_Name(Maintenance_Type);
            int Frecuency = Integer.parseInt(Txt_Frecuencia_Dias.getText());
            double Mileage = Double.parseDouble(Txt_Kilometraje.getText());

            Maintenance_Assigments_Obj Obj = new Maintenance_Assigments_Obj(License_Plate, Maintenance_Type_Id, Part_Id, Frecuency, Mileage);
            int Affected_Rows;
            Affected_Rows = CUD_SQL.Update_Maintenance_Assigments(Obj);
            if (Affected_Rows != 0) {
                Txt_Frecuencia_Dias.setText("");
                Txt_Kilometraje.setText("");
                Jcb_Matricula_Asignacion.setSelectedItem("Seleccione la matricula:");
                Jcb_Nombre_Pieza_Asignacipn.setSelectedItem("Seleccione la pieza");
                Jcb_Id_Mantenimiento.setSelectedItem("Seleccione el mantenimiento");
            }

        } catch (SQLException ex) {
            Logger.getLogger(Mechanics_Section.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Btn_Actualizar_Asignacion_MantenimientoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Actualizar_Asignacion_Mantenimiento;
    private javax.swing.JButton Btn_Actualizar_Boleta_Mantenimiento;
    private javax.swing.JButton Btn_Actualizar_Detalle_Mantenimiento;
    private javax.swing.JButton Btn_Actualizar_Mantenimiento;
    private javax.swing.JButton Btn_Actualizar_Pieza;
    private javax.swing.JButton Btn_Registrar_Asignacion_Mantenimiento;
    private javax.swing.JButton Btn_Registrar_Boleta_Mantenimiento;
    private javax.swing.JButton Btn_Registrar_Detalle_Mantenimiento;
    private javax.swing.JButton Btn_Registrar_Mantenimiento;
    private javax.swing.JButton Btn_Registro_Pieza;
    private datechooser.beans.DateChooserCombo DCC_Fecha;
    private javax.swing.JComboBox<String> Jcb_Chofer;
    private javax.swing.JComboBox<String> Jcb_Id_Boleta;
    private javax.swing.JComboBox<String> Jcb_Id_Mantenimiento;
    private javax.swing.JComboBox<String> Jcb_Matricula_Asignacion;
    private javax.swing.JComboBox<String> Jcb_Matricula_Boleta;
    private javax.swing.JComboBox<String> Jcb_Mecanico;
    private javax.swing.JComboBox<String> Jcb_Nombre_Pieza;
    private javax.swing.JComboBox<String> Jcb_Nombre_Pieza_Asignacipn;
    private javax.swing.JComboBox<String> Jcb_Tipo_Mantenimiento_Detalle;
    private javax.swing.JComboBox<String> Jcb_Vehiculo;
    private javax.swing.JLabel Lbl_Actualizar_Id;
    private javax.swing.JTextArea TxA_Descripcion;
    private javax.swing.JTextField Txt_Categoria_Pieza;
    private javax.swing.JTextField Txt_Compatibilidad;
    private javax.swing.JTextField Txt_Costo_Estimado;
    private javax.swing.JTextField Txt_Frecuencia;
    private javax.swing.JTextField Txt_Frecuencia_Dias;
    private javax.swing.JTextField Txt_Garantia;
    private javax.swing.JTextField Txt_Id;
    private javax.swing.JTextField Txt_Id_Boleta;
    private javax.swing.JTextField Txt_Id_Detalle;
    private javax.swing.JTextField Txt_Id_Mantenimiento;
    private javax.swing.JTextField Txt_Kilometraje;
    private javax.swing.JTextField Txt_Kilometraje_Boleta;
    private javax.swing.JTextField Txt_Manufactura;
    private javax.swing.JTextField Txt_Nombre_Pieza;
    private javax.swing.JTextField Txt_Precio_Unidad;
    private javax.swing.JTextField Txt_Tipo_Mantenimiento;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblContrasena1;
    private javax.swing.JLabel lblContrasena2;
    private javax.swing.JLabel lblContrasena3;
    private javax.swing.JLabel lblContrasena4;
    private javax.swing.JLabel lblIniciarSesion;
    private javax.swing.JLabel lblIniciarSesion1;
    private javax.swing.JLabel lblIniciarSesion10;
    private javax.swing.JLabel lblIniciarSesion11;
    private javax.swing.JLabel lblIniciarSesion12;
    private javax.swing.JLabel lblIniciarSesion14;
    private javax.swing.JLabel lblIniciarSesion15;
    private javax.swing.JLabel lblIniciarSesion16;
    private javax.swing.JLabel lblIniciarSesion17;
    private javax.swing.JLabel lblIniciarSesion18;
    private javax.swing.JLabel lblIniciarSesion19;
    private javax.swing.JLabel lblIniciarSesion2;
    private javax.swing.JLabel lblIniciarSesion20;
    private javax.swing.JLabel lblIniciarSesion21;
    private javax.swing.JLabel lblIniciarSesion22;
    private javax.swing.JLabel lblIniciarSesion28;
    private javax.swing.JLabel lblIniciarSesion3;
    private javax.swing.JLabel lblIniciarSesion30;
    private javax.swing.JLabel lblIniciarSesion31;
    private javax.swing.JLabel lblIniciarSesion32;
    private javax.swing.JLabel lblIniciarSesion33;
    private javax.swing.JLabel lblIniciarSesion4;
    private javax.swing.JLabel lblIniciarSesion5;
    private javax.swing.JLabel lblIniciarSesion6;
    private javax.swing.JLabel lblIniciarSesion7;
    private javax.swing.JLabel lblIniciarSesion8;
    private javax.swing.JLabel lblIniciarSesion9;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuario1;
    private javax.swing.JLabel lblUsuario2;
    // End of variables declaration//GEN-END:variables
}
