/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentation;

import Data.Connection_SQL;
import static Data.Connection_SQL.get_Current_Mileage;
import java.util.Calendar;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.proteanit.sql.DbUtils;

/**
 * /**
 *
 * @author Admin
 */
public class Reports extends javax.swing.JPanel {

    /**
     * Creates new form Reports
     */
    public Reports() throws SQLException {
        initComponents();
        Attention();
        Load_JCB();
        Action_Listener();
        AttentionByMileage();
    }

    private void Action_Listener() {
        JCB.addActionListener(evt -> {
            try {
                Load_Maintenance_Made();
            } catch (SQLException ex) {
                Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
        JCB1.addActionListener(evt -> {
            try {
                Load_Fuel_Performance();
            } catch (SQLException ex) {
                Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
        JCB_2.addActionListener(evt -> {
            try {
                Load_Binnacle();
            } catch (SQLException ex) {
                Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
            }
        });

    }

    private void Load_JCB() throws SQLException {
        Connection_SQL.get_Vehicle_Name(JCB);
        Connection_SQL.get_Vehicle_Name(JCB1);
        Connection_SQL.get_User_Id(JCB_2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tbl_Info2 = new javax.swing.JTable();
        lblIniciarSesion2 = new javax.swing.JLabel();
        JCB1 = new javax.swing.JComboBox<>();
        lblIniciarSesion14 = new javax.swing.JLabel();
        lblIniciarSesion24 = new javax.swing.JLabel();
        CCC_Inicio1 = new datechooser.beans.DateChooserCombo();
        CCB_Final1 = new datechooser.beans.DateChooserCombo();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tbl_Info = new javax.swing.JTable();
        lblIniciarSesion1 = new javax.swing.JLabel();
        JCB = new javax.swing.JComboBox<>();
        lblIniciarSesion13 = new javax.swing.JLabel();
        lblIniciarSesion23 = new javax.swing.JLabel();
        CCC_Inicio = new datechooser.beans.DateChooserCombo();
        CCB_Final = new datechooser.beans.DateChooserCombo();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Tbl_Info1 = new javax.swing.JTable();
        lblIniciarSesion3 = new javax.swing.JLabel();
        JCB_2 = new javax.swing.JComboBox<>();
        lblIniciarSesion15 = new javax.swing.JLabel();
        lblIniciarSesion25 = new javax.swing.JLabel();
        CCC_Inicio2 = new datechooser.beans.DateChooserCombo();
        CCB_Final2 = new datechooser.beans.DateChooserCombo();

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane3.setViewportView(Tbl_Info2);

        jPanel7.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 800, -1));

        lblIniciarSesion2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblIniciarSesion2.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion2.setText("Fecha Final");
        jPanel7.add(lblIniciarSesion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 110, 30));

        JCB1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JCB1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "Combustibles", "Tanques de Combustibles", "Ingreso de Combustibles", "Dispensadores", "Dispensado de Combustible" }));
        jPanel7.add(JCB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 220, -1));

        lblIniciarSesion14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblIniciarSesion14.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion14.setText("Rendimiento de Combustible por Vehiculo");
        jPanel7.add(lblIniciarSesion14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 390, 40));

        lblIniciarSesion24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblIniciarSesion24.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion24.setText("Fecha de Inicio");
        jPanel7.add(lblIniciarSesion24, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 140, 30));
        jPanel7.add(CCC_Inicio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));
        jPanel7.add(CCB_Final1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, -1, -1));

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 760));

        jTabbedPane1.addTab("Rendimiento de Combustible ", jPanel2);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setViewportView(Tbl_Info);

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 800, -1));

        lblIniciarSesion1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblIniciarSesion1.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion1.setText("Fecha Final");
        jPanel6.add(lblIniciarSesion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 110, 30));

        JCB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "Combustibles", "Tanques de Combustibles", "Ingreso de Combustibles", "Dispensadores", "Dispensado de Combustible" }));
        jPanel6.add(JCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 220, -1));

        lblIniciarSesion13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblIniciarSesion13.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion13.setText("Mantenimientos realizados por Vehiculo");
        jPanel6.add(lblIniciarSesion13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 370, 40));

        lblIniciarSesion23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblIniciarSesion23.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion23.setText("Fecha de Inicio");
        jPanel6.add(lblIniciarSesion23, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 140, 30));
        jPanel6.add(CCC_Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));
        jPanel6.add(CCB_Final, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, -1, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 760));

        jTabbedPane1.addTab("Mantenimientos Realizados", jPanel1);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane4.setViewportView(Tbl_Info1);

        jPanel8.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 800, -1));

        lblIniciarSesion3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblIniciarSesion3.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion3.setText("Fecha Final");
        jPanel8.add(lblIniciarSesion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 110, 30));

        JCB_2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JCB_2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion" }));
        jPanel8.add(JCB_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 220, -1));

        lblIniciarSesion15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblIniciarSesion15.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion15.setText("Bitacora");
        jPanel8.add(lblIniciarSesion15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 90, 40));

        lblIniciarSesion25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblIniciarSesion25.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion25.setText("Fecha de Inicio");
        jPanel8.add(lblIniciarSesion25, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 140, 30));
        jPanel8.add(CCC_Inicio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));
        jPanel8.add(CCB_Final2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, -1, -1));

        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 760));

        jTabbedPane1.addTab("Bitacora Movimientos", jPanel4);

        jPanel3.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 791, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void Attention() throws SQLException {
        Date Current_Date = new Date();

        String qry = "SELECT V.License_Plate, H.Date, MA.Frecuency_Days "
                + "FROM Vehicle V "
                + "JOIN Header H ON V.License_Plate = H.Vehicle_License_Plate "
                + "JOIN Maintenance_Assigments MA ON V.License_Plate = MA.License_Plate";

        Statement sql = Connection_SQL.getConnection().createStatement();
        ResultSet rs = sql.executeQuery(qry);

        while (rs.next()) {
            String License_Plate = rs.getString("License_Plate");
            Date Ticket_Date = rs.getDate("Date");
            int Maintenance_Frecuency = rs.getInt("Frecuency_Days");

            if (Ticket_Date != null) {
                // Calcular la proxima fecha de mantenimiento sumando la frecuencia de dias
                Calendar calendar = Calendar.getInstance();
                calendar.setTime(Ticket_Date);
                calendar.add(Calendar.DAY_OF_MONTH, Maintenance_Frecuency);
                Date Next_Maintenance_Date = calendar.getTime();

                // Comparar la fecha actual con la proxima fecha de mantenimiento
                if (Current_Date.after(Next_Maintenance_Date)) {
                    // Si el mnatenimientoe es verdadero, mostrar el mensaje
                    JOptionPane.showMessageDialog(null, "El vehiculo con matrícula " + License_Plate + " tiene mantenimiento pendiente.",
                            "ATENCION!", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }

    private void AttentionByMileage() throws SQLException {
     
    }

    private void Load_Maintenance_Made() throws SQLException {
        String License_Plate = (String) JCB.getSelectedItem();

        Date Start_Date = CCC_Inicio.getSelectedDate().getTime();
        Date End_Date = CCB_Final.getSelectedDate().getTime();
        ResultSet rs = Connection_SQL.get_Vehicle_Movements(Start_Date, End_Date, License_Plate);
        Tbl_Info.setModel(DbUtils.resultSetToTableModel(rs));
    }

    private void Load_Fuel_Performance() throws SQLException {
        String License_Plate = (String) JCB1.getSelectedItem();

        Date Start_Date = CCC_Inicio1.getSelectedDate().getTime();
        Date End_Date = CCB_Final1.getSelectedDate().getTime();
        ResultSet rs = Connection_SQL.get_Fuel_Performance(Start_Date, End_Date, License_Plate);
        Tbl_Info2.setModel(DbUtils.resultSetToTableModel(rs));
    }

    private void Load_Binnacle() throws SQLException {
        String License_Plate = (String) JCB_2.getSelectedItem();

        Date Start_Date = CCC_Inicio2.getSelectedDate().getTime();
        Date End_Date = CCB_Final2.getSelectedDate().getTime();
        ResultSet rs = Connection_SQL.get_Fuel_Performance(Start_Date, End_Date, License_Plate);
        Tbl_Info1.setModel(DbUtils.resultSetToTableModel(rs));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo CCB_Final;
    private datechooser.beans.DateChooserCombo CCB_Final1;
    private datechooser.beans.DateChooserCombo CCB_Final2;
    private datechooser.beans.DateChooserCombo CCC_Inicio;
    private datechooser.beans.DateChooserCombo CCC_Inicio1;
    private datechooser.beans.DateChooserCombo CCC_Inicio2;
    private javax.swing.JComboBox<String> JCB;
    private javax.swing.JComboBox<String> JCB1;
    private javax.swing.JComboBox<String> JCB_2;
    private javax.swing.JTable Tbl_Info;
    private javax.swing.JTable Tbl_Info1;
    private javax.swing.JTable Tbl_Info2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblIniciarSesion1;
    private javax.swing.JLabel lblIniciarSesion13;
    private javax.swing.JLabel lblIniciarSesion14;
    private javax.swing.JLabel lblIniciarSesion15;
    private javax.swing.JLabel lblIniciarSesion2;
    private javax.swing.JLabel lblIniciarSesion23;
    private javax.swing.JLabel lblIniciarSesion24;
    private javax.swing.JLabel lblIniciarSesion25;
    private javax.swing.JLabel lblIniciarSesion3;
    // End of variables declaration//GEN-END:variables
}
